/**
 * Canape Theme Base Schema
 *
 * The foundational SchemaContract for the Canape restaurant/food theme.
 * All Canape-generated apps start with these 8 tables.
 * User-requested features are merged into this base schema.
 */

import type { SchemaContract } from '../schema-contract'

export const CANAPE_BASE_SCHEMA: SchemaContract = {
  name: 'canape_restaurant',
  tables: [
    {
      name: 'entities',
      displayName: 'Featured Items',
      columns: [
        {
          name: 'id',
          displayName: 'ID',
          type: 'uuid',
          nullable: false,
          primaryKey: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'name',
          displayName: 'Name',
          type: 'text',
          nullable: false,
        },
        {
          name: 'slug',
          displayName: 'Slug',
          type: 'text',
          nullable: false,
          unique: true,
        },
        {
          name: 'description',
          displayName: 'Description',
          type: 'text',
          nullable: true,
        },
        {
          name: 'image_url',
          displayName: 'Image URL',
          type: 'text',
          nullable: true,
        },
        {
          name: 'created_at',
          displayName: 'Created',
          type: 'timestamp',
          nullable: false,
          default: 'now()',
        },
      ],
    },
    {
      name: 'menu_items',
      displayName: 'Menu Items',
      columns: [
        {
          name: 'id',
          displayName: 'ID',
          type: 'uuid',
          nullable: false,
          primaryKey: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'name',
          displayName: 'Item Name',
          type: 'text',
          nullable: false,
        },
        {
          name: 'description',
          displayName: 'Description',
          type: 'text',
          nullable: true,
        },
        {
          name: 'category',
          displayName: 'Category',
          type: 'text',
          nullable: false,
        },
        {
          name: 'price',
          displayName: 'Price',
          type: 'numeric',
          nullable: false,
        },
        {
          name: 'created_at',
          displayName: 'Created',
          type: 'timestamp',
          nullable: false,
          default: 'now()',
        },
      ],
    },
    {
      name: 'posts',
      displayName: 'News & Blog Posts',
      columns: [
        {
          name: 'id',
          displayName: 'ID',
          type: 'uuid',
          nullable: false,
          primaryKey: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'title',
          displayName: 'Title',
          type: 'text',
          nullable: false,
        },
        {
          name: 'slug',
          displayName: 'Slug',
          type: 'text',
          nullable: false,
          unique: true,
        },
        {
          name: 'content',
          displayName: 'Content',
          type: 'text',
          nullable: false,
        },
        {
          name: 'excerpt',
          displayName: 'Excerpt',
          type: 'text',
          nullable: true,
        },
        {
          name: 'featured_image',
          displayName: 'Featured Image',
          type: 'text',
          nullable: true,
        },
        {
          name: 'featured',
          displayName: 'Featured',
          type: 'boolean',
          nullable: false,
          default: 'false',
        },
        {
          name: 'published_at',
          displayName: 'Published',
          type: 'timestamp',
          nullable: true,
        },
        {
          name: 'comment_count',
          displayName: 'Comment Count',
          type: 'integer',
          nullable: false,
          default: '0',
        },
        {
          name: 'created_at',
          displayName: 'Created',
          type: 'timestamp',
          nullable: false,
          default: 'now()',
        },
      ],
    },
    {
      name: 'comments',
      displayName: 'Comments',
      columns: [
        {
          name: 'id',
          displayName: 'ID',
          type: 'uuid',
          nullable: false,
          primaryKey: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'post_id',
          displayName: 'Post ID',
          type: 'uuid',
          nullable: false,
          references: { table: 'posts', column: 'id' },
        },
        {
          name: 'author_name',
          displayName: 'Author Name',
          type: 'text',
          nullable: false,
        },
        {
          name: 'author_email',
          displayName: 'Author Email',
          type: 'text',
          nullable: false,
        },
        {
          name: 'content',
          displayName: 'Content',
          type: 'text',
          nullable: false,
        },
        {
          name: 'created_at',
          displayName: 'Created',
          type: 'timestamp',
          nullable: false,
          default: 'now()',
        },
      ],
    },
    {
      name: 'testimonials',
      displayName: 'Testimonials',
      columns: [
        {
          name: 'id',
          displayName: 'ID',
          type: 'uuid',
          nullable: false,
          primaryKey: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'quote',
          displayName: 'Quote',
          type: 'text',
          nullable: false,
        },
        {
          name: 'author_name',
          displayName: 'Author Name',
          type: 'text',
          nullable: false,
        },
        {
          name: 'created_at',
          displayName: 'Created',
          type: 'timestamp',
          nullable: false,
          default: 'now()',
        },
      ],
    },
    {
      name: 'services_page',
      displayName: 'Services',
      columns: [
        {
          name: 'id',
          displayName: 'ID',
          type: 'uuid',
          nullable: false,
          primaryKey: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'name',
          displayName: 'Service Name',
          type: 'text',
          nullable: false,
        },
        {
          name: 'url',
          displayName: 'URL',
          type: 'text',
          nullable: true,
        },
        {
          name: 'order_index',
          displayName: 'Order',
          type: 'integer',
          nullable: false,
          default: '0',
        },
        {
          name: 'created_at',
          displayName: 'Created',
          type: 'timestamp',
          nullable: false,
          default: 'now()',
        },
      ],
    },
    {
      name: 'pages',
      displayName: 'Static Pages',
      columns: [
        {
          name: 'id',
          displayName: 'ID',
          type: 'uuid',
          nullable: false,
          primaryKey: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'title',
          displayName: 'Title',
          type: 'text',
          nullable: false,
        },
        {
          name: 'slug',
          displayName: 'Slug',
          type: 'text',
          nullable: false,
          unique: true,
        },
        {
          name: 'content',
          displayName: 'Content',
          type: 'text',
          nullable: false,
        },
        {
          name: 'created_at',
          displayName: 'Created',
          type: 'timestamp',
          nullable: false,
          default: 'now()',
        },
      ],
    },
    {
      name: 'site_settings',
      displayName: 'Site Settings',
      columns: [
        {
          name: 'id',
          displayName: 'ID',
          type: 'uuid',
          nullable: false,
          primaryKey: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'contact_email',
          displayName: 'Contact Email',
          type: 'text',
          nullable: true,
        },
        {
          name: 'phone',
          displayName: 'Phone',
          type: 'text',
          nullable: true,
        },
        {
          name: 'address',
          displayName: 'Address',
          type: 'text',
          nullable: true,
        },
        {
          name: 'hours_lunch',
          displayName: 'Lunch Hours',
          type: 'text',
          nullable: true,
        },
        {
          name: 'hours_dinner',
          displayName: 'Dinner Hours',
          type: 'text',
          nullable: true,
        },
        {
          name: 'lunch_start',
          displayName: 'Lunch Start',
          type: 'text',
          nullable: true,
        },
        {
          name: 'lunch_end',
          displayName: 'Lunch End',
          type: 'text',
          nullable: true,
        },
        {
          name: 'dinner_mon_thu_start',
          displayName: 'Dinner Mon-Thu Start',
          type: 'text',
          nullable: true,
        },
        {
          name: 'dinner_mon_thu_end',
          displayName: 'Dinner Mon-Thu End',
          type: 'text',
          nullable: true,
        },
        {
          name: 'dinner_fri_sat_start',
          displayName: 'Dinner Fri-Sat Start',
          type: 'text',
          nullable: true,
        },
        {
          name: 'dinner_fri_sat_end',
          displayName: 'Dinner Fri-Sat End',
          type: 'text',
          nullable: true,
        },
        {
          name: 'created_at',
          displayName: 'Created',
          type: 'timestamp',
          nullable: false,
          default: 'now()',
        },
      ],
    },
    {
      name: 'reservations',
      displayName: 'Reservations',
      columns: [
        {
          name: 'id',
          displayName: 'ID',
          type: 'uuid',
          nullable: false,
          primaryKey: true,
          default: 'gen_random_uuid()',
        },
        {
          name: 'name',
          displayName: 'Name',
          type: 'text',
          nullable: false,
        },
        {
          name: 'email',
          displayName: 'Email',
          type: 'text',
          nullable: false,
        },
        {
          name: 'phone',
          displayName: 'Phone',
          type: 'text',
          nullable: true,
        },
        {
          name: 'party_size',
          displayName: 'Party Size',
          type: 'integer',
          nullable: false,
        },
        {
          name: 'date',
          displayName: 'Date',
          type: 'date',
          nullable: false,
        },
        {
          name: 'time',
          displayName: 'Time',
          type: 'text',
          nullable: false,
        },
        {
          name: 'requests',
          displayName: 'Special Requests',
          type: 'text',
          nullable: true,
        },
        {
          name: 'created_at',
          displayName: 'Created',
          type: 'timestamp',
          nullable: false,
          default: 'now()',
        },
      ],
    },
  ],
}
