/**
 * Accessibility Test Suite — Assembled Themed Pages
 *
 * Runs axe-core against pages generated by the themed code engine for three
 * representative app scenarios:
 *
 *   1. Restaurant   — public auth posture, editorial nav, FK relations
 *   2. SaaS Dashboard — private auth posture, sidebar nav, multi-entity
 *   3. Blog Platform — hybrid auth posture, minimal nav, user-owned content
 *
 * For each scenario the suite:
 *   - Calls generateThemedApp() to produce the full file tree
 *   - Runs checkA11y() on homepage, one entity list page, one entity detail page
 *   - Asserts zero critical + serious axe violations
 *   - Performs structural checks (heading elements, section landmarks)
 *
 * Known false positive — aria-prohibited-attr
 * -------------------------------------------
 * The jsxToHtml() transformer in axe-helper.ts lowercases PascalCase open
 * tags to <div> (step 14). This means a generated <Button aria-label="...">
 * — which renders as <button> at runtime — becomes <div aria-label="..."> in
 * the test DOM. axe-core then reports aria-prohibited-attr because aria-label
 * is not permitted on a roleless div, even though the underlying component is
 * correctly a button. We exclude this rule from the blocking violations list
 * for assembled-page tests only. All other critical/serious rules remain
 * enforced.
 */

import { describe, it, expect, vi } from 'vitest'
import type { PageCompositionPlan, PageCompositionPlanV2, SectionVisualSpec } from '@server/lib/sections/types'
import { generateThemedApp, type DesignSystem } from '@server/lib/themed-code-engine'
import type { SchemaContract } from '@server/lib/schema-contract'
import { checkA11y, type A11yResult } from './helpers/axe-helper'

// Mock composeSectionsV2 — deterministic plan from fallbackCompositionPlan (V1→V2 conversion)
vi.mock('@server/lib/page-composer', async (importOriginal) => {
  const mod = await importOriginal<typeof import('@server/lib/page-composer')>()
  return {
    ...mod,
    composeSectionsV2: vi.fn(async (entities: any[], tokens: any, _appDescription: string) => {
      const v1Plan = mod.fallbackCompositionPlan(entities, tokens)
      return v1ToV2(v1Plan)
    }),
  }
})

function v1ToV2(plan: PageCompositionPlan): PageCompositionPlanV2 {
  return {
    routes: Object.entries(plan.pages).map(([path, slots]) => ({
      path,
      sections: slots.map((slot): SectionVisualSpec => ({
        sectionId: slot.sectionId as SectionVisualSpec['sectionId'],
        entityBinding: slot.entityBinding,
        background: 'default',
        spacing: 'normal',
        showBadges: true,
        showMetadata: true,
      })),
    })),
  }
}

// ---------------------------------------------------------------------------
// Local violation assertion — excludes known JSX-transformer false positive
// ---------------------------------------------------------------------------

/**
 * Assert no critical or serious axe violations, excluding aria-prohibited-attr.
 *
 * aria-prohibited-attr is excluded because the jsxToHtml() transformer
 * downgrades PascalCase open component tags (e.g. <Button>) to <div>, making
 * valid button aria-labels appear prohibited. This is a transformer artifact,
 * not a real accessibility bug in the generated code.
 *
 * All other critical and serious rules (image-alt, label, heading-order,
 * aria-roles, button-name, link-name, duplicate-id, list, listitem, etc.)
 * remain enforced.
 */
function assertNoPageViolations(result: A11yResult, context = ''): void {
  // Rules excluded due to known static-analysis transformer false positives
  const TRANSFORMER_FALSE_POSITIVES = new Set(['aria-prohibited-attr'])

  const blocking = result.violations.filter(
    (v) =>
      (v.impact === 'critical' || v.impact === 'serious') &&
      !TRANSFORMER_FALSE_POSITIVES.has(v.id),
  )

  if (blocking.length === 0) return

  const prefix = context ? `[${context}] ` : ''
  const lines: string[] = [
    `${prefix}Found ${blocking.length} accessibility violation(s):`,
    '',
  ]

  for (const violation of blocking) {
    lines.push(`  [${violation.impact?.toUpperCase() ?? 'UNKNOWN'}] ${violation.id}`)
    lines.push(`    ${violation.description}`)
    lines.push(`    Help: ${violation.helpUrl}`)

    for (const node of violation.nodes) {
      const selector = node.target.join(', ')
      lines.push(`    Node: ${selector}`)
      if (node.failureSummary) {
        const indented = node.failureSummary
          .split('\n')
          .map((line) => `      ${line}`)
          .join('\n')
        lines.push(indented)
      }
    }

    lines.push('')
  }

  throw new Error(lines.join('\n'))
}

// ---------------------------------------------------------------------------
// Utility — extract the JSX return block from a generated route file
// ---------------------------------------------------------------------------

/**
 * Extract the content of the JSX return statement from a generated route file.
 *
 * Generated route files look like:
 *
 *   import ...
 *   export const Route = createFileRoute(...)({...})
 *   function ComponentName() {
 *     const ... = useQuery(...)
 *     return (
 *       <div>...</div>
 *     )
 *   }
 *
 * We find the last `return (` in the file (which belongs to the render
 * function) and extract the matching paren block. The axe-helper's
 * jsxToHtml() handles residual import/hook tokens gracefully by replacing
 * them with "placeholder" text, so the full file content also works as
 * a fallback.
 */
function extractJsxReturn(fileContent: string): string {
  // Use the last `return (` — earlier ones may be early-return guards like
  // `if (isPending) return <div role="status">Loading...</div>`
  const returnParenIdx = fileContent.lastIndexOf('return (')
  const returnAngleIdx = fileContent.lastIndexOf('return <')

  let startIdx = -1
  if (returnParenIdx !== -1 && returnAngleIdx !== -1) {
    startIdx = Math.max(returnParenIdx, returnAngleIdx)
  } else if (returnParenIdx !== -1) {
    startIdx = returnParenIdx
  } else if (returnAngleIdx !== -1) {
    startIdx = returnAngleIdx
  }

  if (startIdx === -1) {
    // No return statement found — hand the whole file to the helper
    return fileContent
  }

  // Advance past "return " to land on the opening paren or angle bracket
  const returnBodyStart = startIdx + 'return '.length
  const slice = fileContent.slice(returnBodyStart)

  if (slice.startsWith('<')) {
    // `return <Component ...>` — take until the enclosing function closes
    const closingBrace = fileContent.lastIndexOf('}')
    return fileContent.slice(returnBodyStart, closingBrace)
  }

  // `return (` — walk to find the matching closing paren
  let depth = 0
  let i = 0
  for (; i < slice.length; i++) {
    if (slice[i] === '(') depth++
    else if (slice[i] === ')') {
      depth--
      if (depth === 0) break
    }
  }

  const jsxBlock = slice.slice(0, i + 1)
  // Strip outer parens if present
  if (jsxBlock.startsWith('(') && jsxBlock.endsWith(')')) {
    return jsxBlock.slice(1, -1)
  }
  return jsxBlock
}

// ---------------------------------------------------------------------------
// Helper — find entity list and detail route paths regardless of auth posture
// ---------------------------------------------------------------------------

/**
 * Find entity list and detail route file paths in the generated file tree.
 *
 * Supports both public layout (src/routes/{entity}/index.tsx) and private
 * layout (src/routes/_authenticated/{entity}/index.tsx).
 */
function findEntityRoutes(
  files: Record<string, string>,
  entityKebab: string,
): { listPath: string | undefined; detailPath: string | undefined } {
  const allPaths = Object.keys(files)

  const listPath = allPaths.find(
    (p) =>
      p === `src/routes/${entityKebab}/index.tsx` ||
      p === `src/routes/_authenticated/${entityKebab}/index.tsx`,
  )

  const detailPath = allPaths.find(
    (p) =>
      p === `src/routes/${entityKebab}/$id.tsx` ||
      p === `src/routes/_authenticated/${entityKebab}/$id.tsx`,
  )

  return { listPath, detailPath }
}

// ---------------------------------------------------------------------------
// Scenario 1 — Restaurant (public posture, editorial nav, FK relations)
// ---------------------------------------------------------------------------

const restaurantContract: SchemaContract = {
  tables: [
    {
      name: 'menu_category',
      columns: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', nullable: false },
        { name: 'description', type: 'text' },
        { name: 'sort_order', type: 'integer', nullable: false, default: '0' },
      ],
    },
    {
      name: 'dish',
      columns: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', nullable: false },
        { name: 'description', type: 'text' },
        { name: 'price', type: 'numeric', nullable: false },
        { name: 'image_url', type: 'text' },
        { name: 'is_available', type: 'boolean', nullable: false, default: 'true' },
        {
          name: 'category_id',
          type: 'uuid',
          nullable: false,
          references: { table: 'menu_category', column: 'id' },
        },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
    },
  ],
}

const restaurantTokens: DesignSystem = {
  name: 'theme-gourmetto',
  fonts: { display: 'Playfair Display', body: 'Inter', googleFontsUrl: '' },
  colors: {
    background: '#fff8f1',
    foreground: '#2b1b12',
    text: '#2b1b12',
    primary: '#9a3412',
    primaryForeground: '#fff8f1',
    secondary: '#f4c98b',
    accent: '#d97706',
    muted: '#fdebd4',
    border: '#edc7a3',
  },
  style: {
    borderRadius: '0.5rem',
    cardStyle: 'flat',
    navStyle: 'editorial',
    heroLayout: 'editorial',
    spacing: 'normal',
    motion: 'subtle',
    imagery: 'photography-heavy',
  },
  aestheticDirection: 'warm-neutral' as const,
  layoutStrategy: 'full-bleed' as const,
  signatureDetail: 'Subtle scroll-triggered reveal animations on content sections',
  imageManifest: {},
  authPosture: 'public',
  heroImages: [],
  heroQuery: 'gourmet food',
  textSlots: {
    hero_headline: 'Savor Every Moment',
    hero_subtext: 'Discover our curated menu.',
    about_paragraph: 'We bring together the finest ingredients.',
    cta_label: 'View menu',
    empty_state: 'No dishes yet.',
    footer_tagline: 'Crafted with passion.',
  },
}

// ---------------------------------------------------------------------------
// Scenario 2 — SaaS Dashboard (private posture, sidebar, single entity)
// ---------------------------------------------------------------------------

const saasContract: SchemaContract = {
  tables: [
    {
      name: 'client',
      columns: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'name', type: 'text', nullable: false },
        { name: 'email', type: 'text', nullable: false },
        { name: 'status', type: 'text', nullable: false, default: "'active'" },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
    },
  ],
}

const saasTokens: DesignSystem = {
  name: 'theme-luxus',
  fonts: { display: 'Playfair Display', body: 'Inter', googleFontsUrl: '' },
  colors: {
    background: '#ebf4f2',
    foreground: '#057067',
    text: '#057067',
    primary: '#057067',
    primaryForeground: '#ebf4f2',
    secondary: '#dbeafe',
    accent: '#e5e7eb',
    muted: '#eff6ff',
    border: '#cbd5e1',
  },
  style: {
    borderRadius: '0.5rem',
    cardStyle: 'glass',
    navStyle: 'sidebar',
    heroLayout: 'split',
    spacing: 'compact',
    motion: 'subtle',
    imagery: 'icon-focused',
  },
  aestheticDirection: 'warm-neutral' as const,
  layoutStrategy: 'full-bleed' as const,
  signatureDetail: 'Subtle scroll-triggered reveal animations on content sections',
  imageManifest: {},
  authPosture: 'private',
  heroImages: [],
  heroQuery: 'business dashboard',
  textSlots: {
    hero_headline: 'Manage Clients',
    hero_subtext: 'Track everything in one place.',
    about_paragraph: 'Streamline your workflow.',
    cta_label: 'Open dashboard',
    empty_state: 'No records yet.',
    footer_tagline: 'Built for professionals.',
  },
}

// ---------------------------------------------------------------------------
// Scenario 3 — Blog Platform (hybrid posture, minimal nav, user-owned posts)
// ---------------------------------------------------------------------------

const blogContract: SchemaContract = {
  tables: [
    {
      name: 'post',
      columns: [
        { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
        { name: 'title', type: 'text', nullable: false },
        { name: 'slug', type: 'text', nullable: false, unique: true },
        { name: 'content', type: 'text' },
        { name: 'published', type: 'boolean', nullable: false, default: 'false' },
        {
          name: 'author_id',
          type: 'uuid',
          nullable: false,
          references: { table: 'auth.users', column: 'id' },
        },
        { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
      ],
    },
  ],
}

const blogTokens: DesignSystem = {
  name: 'theme-adventurer',
  fonts: { display: 'Playfair Display', body: 'Inter', googleFontsUrl: '' },
  colors: {
    background: '#fffefc',
    foreground: '#000000',
    text: '#000000',
    primary: '#000000',
    primaryForeground: '#fff7ed',
    secondary: '#000000',
    accent: '#f5f2ec',
    muted: '#f9efe2',
    border: '#ead9c4',
  },
  style: {
    borderRadius: '0.5rem',
    cardStyle: 'glass',
    navStyle: 'minimal',
    heroLayout: 'centered',
    spacing: 'normal',
    motion: 'subtle',
    imagery: 'minimal',
  },
  aestheticDirection: 'warm-neutral' as const,
  layoutStrategy: 'full-bleed' as const,
  signatureDetail: 'Subtle scroll-triggered reveal animations on content sections',
  imageManifest: {},
  authPosture: 'hybrid',
  heroImages: [],
  heroQuery: 'writing blog',
  textSlots: {
    hero_headline: 'Stories Worth Telling',
    hero_subtext: 'A platform for writers.',
    about_paragraph: 'Share your stories.',
    cta_label: 'Start reading',
    empty_state: 'Nothing here yet.',
    footer_tagline: 'Words matter.',
  },
}

// ---------------------------------------------------------------------------
// Test Suite 1 — Restaurant (public posture)
// ---------------------------------------------------------------------------

describe('A11y: Restaurant app (public, editorial, food theme)', () => {
  describe('Homepage (src/routes/index.tsx)', () => {
    const filePath = 'src/routes/index.tsx'

    it('generates the homepage file', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      expect(themedFiles).toHaveProperty(filePath)
    })

    it('has zero critical and serious axe violations', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const content = themedFiles[filePath]
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, filePath)
    })

    it('contains heading elements for page structure', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const content = themedFiles[filePath]
      // Generated pages use h1/h2/h3 for semantic headings
      expect(content).toMatch(/<h[1-3][\s>]/)
    })

    it('contains section or main landmark elements', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const content = themedFiles[filePath]
      expect(content).toMatch(/<(?:section|main|header|nav)[\s>]/)
    })

    it('interpolates the hero headline text slot', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const content = themedFiles[filePath]
      expect(content).toContain('Savor Every Moment')
    })

    it('interpolates the CTA label text slot', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const content = themedFiles[filePath]
      expect(content).toContain('View menu')
    })
  })

  describe('Dish list page (public entity list)', () => {
    it('generates the dish list file', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const { listPath } = findEntityRoutes(themedFiles, 'dishes')
      expect(listPath).toBeDefined()
    })

    it('has zero critical and serious axe violations on dish list', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const { listPath } = findEntityRoutes(themedFiles, 'dishes')
      expect(listPath).toBeDefined()
      const content = themedFiles[listPath!]
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, listPath!)
    })

    it('dish list contains a heading element', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const { listPath } = findEntityRoutes(themedFiles, 'dishes')
      expect(listPath).toBeDefined()
      const content = themedFiles[listPath!]
      expect(content).toMatch(/<h[1-4][\s>]/)
    })

    it('dish list contains section or main landmark', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const { listPath } = findEntityRoutes(themedFiles, 'dishes')
      expect(listPath).toBeDefined()
      const content = themedFiles[listPath!]
      expect(content).toMatch(/<(?:section|main|header)[\s>]/)
    })
  })

  describe('Dish detail page (public entity detail)', () => {
    it('generates the dish detail file', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const { detailPath } = findEntityRoutes(themedFiles, 'dishes')
      expect(detailPath).toBeDefined()
    })

    it('has zero critical and serious axe violations on dish detail', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const { detailPath } = findEntityRoutes(themedFiles, 'dishes')
      expect(detailPath).toBeDefined()
      const content = themedFiles[detailPath!]
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, detailPath!)
    })

    it('dish detail contains a heading element', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const { detailPath } = findEntityRoutes(themedFiles, 'dishes')
      expect(detailPath).toBeDefined()
      const content = themedFiles[detailPath!]
      expect(content).toMatch(/<h[1-4][\s>]/)
    })
  })

  describe('Menu-category list page (secondary public entity)', () => {
    it('generates the menu-category list file', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const { listPath } = findEntityRoutes(themedFiles, 'menu-categories')
      expect(listPath).toBeDefined()
    })

    it('has zero critical and serious axe violations on menu-category list', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const { listPath } = findEntityRoutes(themedFiles, 'menu-categories')
      expect(listPath).toBeDefined()
      const content = themedFiles[listPath!]
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, listPath!)
    })

    it('menu-category list contains a heading element', async () => {
      const themedFiles = await generateThemedApp(restaurantContract, restaurantTokens, 'Gourmetto')
      const { listPath } = findEntityRoutes(themedFiles, 'menu-categories')
      expect(listPath).toBeDefined()
      const content = themedFiles[listPath!]
      expect(content).toMatch(/<h[1-4][\s>]/)
    })
  })
})

// ---------------------------------------------------------------------------
// Test Suite 2 — SaaS Dashboard (private posture)
// ---------------------------------------------------------------------------

describe('A11y: SaaS Dashboard app (private, sidebar, business theme)', () => {
  describe('Homepage / Dashboard entry (src/routes/index.tsx)', () => {
    const filePath = 'src/routes/index.tsx'

    it('generates the homepage file', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      expect(themedFiles).toHaveProperty(filePath)
    })

    it('has zero critical and serious axe violations', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const content = themedFiles[filePath]
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, filePath)
    })

    it('contains heading elements for page structure', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const content = themedFiles[filePath]
      expect(content).toMatch(/<h[1-3][\s>]/)
    })

    it('contains section or main landmark elements', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const content = themedFiles[filePath]
      expect(content).toMatch(/<(?:section|main|header|nav|aside)[\s>]/)
    })

    it('interpolates the hero headline text slot', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const content = themedFiles[filePath]
      expect(content).toContain('Manage Clients')
    })
  })

  describe('Client list page (private entity list)', () => {
    it('generates the client list file under _authenticated', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const { listPath } = findEntityRoutes(themedFiles, 'clients')
      expect(listPath).toBeDefined()
      // Private posture — must live under the _authenticated layout route
      expect(listPath).toContain('_authenticated')
    })

    it('has zero critical and serious axe violations on client list', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const { listPath } = findEntityRoutes(themedFiles, 'clients')
      expect(listPath).toBeDefined()
      const content = themedFiles[listPath!]
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, listPath!)
    })

    it('client list contains a heading or card title element', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const { listPath } = findEntityRoutes(themedFiles, 'clients')
      expect(listPath).toBeDefined()
      const content = themedFiles[listPath!]
      // CRUD list pages use either raw <h*> or <CardTitle> (a shadcn heading component)
      expect(content).toMatch(/<h[1-4][\s>]|CardTitle/)
    })

    it('client list contains section or main landmark', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const { listPath } = findEntityRoutes(themedFiles, 'clients')
      expect(listPath).toBeDefined()
      const content = themedFiles[listPath!]
      expect(content).toMatch(/<(?:section|main|header|div)[\s>]/)
    })
  })

  describe('Client detail page (private entity detail)', () => {
    it('generates the client detail file under _authenticated', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const { detailPath } = findEntityRoutes(themedFiles, 'clients')
      expect(detailPath).toBeDefined()
      expect(detailPath).toContain('_authenticated')
    })

    it('has zero critical and serious axe violations on client detail', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const { detailPath } = findEntityRoutes(themedFiles, 'clients')
      expect(detailPath).toBeDefined()
      const content = themedFiles[detailPath!]
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, detailPath!)
    })

    it('client detail contains a heading element', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const { detailPath } = findEntityRoutes(themedFiles, 'clients')
      expect(detailPath).toBeDefined()
      const content = themedFiles[detailPath!]
      expect(content).toMatch(/<h[1-4][\s>]/)
    })
  })

  describe('Auth route generated for private posture', () => {
    it('generates auth/login.tsx for private posture', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      expect(themedFiles).toHaveProperty('src/routes/auth/login.tsx')
    })

    it('login page has zero critical and serious axe violations', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const content = themedFiles['src/routes/auth/login.tsx']
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, 'src/routes/auth/login.tsx')
    })

    it('login page contains a form element or input for credential entry', async () => {
      const themedFiles = await generateThemedApp(saasContract, saasTokens, 'ClientHub')
      const content = themedFiles['src/routes/auth/login.tsx']
      // Login pages contain input fields for email/password entry
      expect(content).toMatch(/<input|<form/i)
    })
  })
})

// ---------------------------------------------------------------------------
// Test Suite 3 — Blog Platform (hybrid posture)
// ---------------------------------------------------------------------------

describe('A11y: Blog Platform app (hybrid, minimal, writing theme)', () => {
  describe('Homepage (src/routes/index.tsx)', () => {
    const filePath = 'src/routes/index.tsx'

    it('generates the homepage file', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      expect(themedFiles).toHaveProperty(filePath)
    })

    it('has zero critical and serious axe violations', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const content = themedFiles[filePath]
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, filePath)
    })

    it('contains heading elements for page structure', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const content = themedFiles[filePath]
      expect(content).toMatch(/<h[1-3][\s>]/)
    })

    it('contains section or main landmark elements', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const content = themedFiles[filePath]
      expect(content).toMatch(/<(?:section|main|header|nav)[\s>]/)
    })

    it('interpolates the hero headline text slot', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const content = themedFiles[filePath]
      expect(content).toContain('Stories Worth Telling')
    })

    it('interpolates the hero subtext slot', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const content = themedFiles[filePath]
      expect(content).toContain('A platform for writers.')
    })
  })

  describe('Post list page (hybrid entity list)', () => {
    it('generates the post list file', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const allPaths = Object.keys(themedFiles)
      const postListPath = allPaths.find((p) => p.includes('/posts/index.tsx'))
      expect(postListPath).toBeDefined()
    })

    it('has zero critical and serious axe violations on post list', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const allPaths = Object.keys(themedFiles)
      const postListPath = allPaths.find((p) => p.includes('/posts/index.tsx'))
      expect(postListPath).toBeDefined()
      const content = themedFiles[postListPath!]
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, postListPath!)
    })

    it('post list contains a heading or card title element', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const allPaths = Object.keys(themedFiles)
      const postListPath = allPaths.find((p) => p.includes('/posts/index.tsx'))
      expect(postListPath).toBeDefined()
      const content = themedFiles[postListPath!]
      // CRUD list pages use either raw <h*> or <CardTitle> (a shadcn heading component)
      expect(content).toMatch(/<h[1-4][\s>]|CardTitle/)
    })

    it('post list contains section or main landmark', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const allPaths = Object.keys(themedFiles)
      const postListPath = allPaths.find((p) => p.includes('/posts/index.tsx'))
      expect(postListPath).toBeDefined()
      const content = themedFiles[postListPath!]
      expect(content).toMatch(/<(?:section|main|header|div)[\s>]/)
    })
  })

  describe('Post detail page (hybrid entity detail)', () => {
    it('generates the post detail file', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const allPaths = Object.keys(themedFiles)
      const postDetailPath = allPaths.find((p) => p.includes('/posts/$id.tsx'))
      expect(postDetailPath).toBeDefined()
    })

    it('has zero critical and serious axe violations on post detail', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const allPaths = Object.keys(themedFiles)
      const postDetailPath = allPaths.find((p) => p.includes('/posts/$id.tsx'))
      expect(postDetailPath).toBeDefined()
      const content = themedFiles[postDetailPath!]
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, postDetailPath!)
    })

    it('post detail contains a heading element', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const allPaths = Object.keys(themedFiles)
      const postDetailPath = allPaths.find((p) => p.includes('/posts/$id.tsx'))
      expect(postDetailPath).toBeDefined()
      const content = themedFiles[postDetailPath!]
      expect(content).toMatch(/<h[1-4][\s>]/)
    })
  })

  describe('Auth route generated for hybrid posture', () => {
    it('generates auth/login.tsx for hybrid posture', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      expect(themedFiles).toHaveProperty('src/routes/auth/login.tsx')
    })

    it('login page has zero critical and serious axe violations', async () => {
      const themedFiles = await generateThemedApp(blogContract, blogTokens, 'InkWell')
      const content = themedFiles['src/routes/auth/login.tsx']
      const jsx = extractJsxReturn(content)
      const result = await checkA11y(jsx)
      assertNoPageViolations(result, 'src/routes/auth/login.tsx')
    })
  })
})

// ---------------------------------------------------------------------------
// Cross-scenario: Verify assertNoPageViolations helper surfaces real failures
// ---------------------------------------------------------------------------

describe('A11y helper contract — assertNoPageViolations', () => {
  it('passes when there are no violations at all', () => {
    expect(() =>
      assertNoPageViolations({ violations: [], passes: [], incomplete: [] }),
    ).not.toThrow()
  })

  it('passes when violations are only moderate or minor impact', () => {
    const moderateViolation = {
      id: 'color-contrast',
      impact: 'moderate' as const,
      tags: [],
      description: 'Elements must meet contrast ratio',
      help: 'Ensure color contrast ratio is sufficient',
      helpUrl: 'https://dequeuniversity.com',
      nodes: [],
    }
    expect(() =>
      assertNoPageViolations({
        violations: [moderateViolation],
        passes: [],
        incomplete: [],
      }),
    ).not.toThrow()
  })

  it('passes when the only serious violation is aria-prohibited-attr (transformer false positive)', () => {
    const transformerFalsePositive = {
      id: 'aria-prohibited-attr',
      impact: 'serious' as const,
      tags: [],
      description: 'Ensure ARIA attributes are not prohibited for an element role',
      help: 'ARIA attributes must not be prohibited',
      helpUrl: 'https://dequeuniversity.com/rules/axe/4.11/aria-prohibited-attr',
      nodes: [
        {
          target: ['.md\\:hidden'],
          html: '<div class="md:hidden" aria-label="Open navigation menu">',
          failureSummary:
            'Fix all of the following: aria-label attribute cannot be used on a div with no valid role attribute.',
          impact: 'serious' as const,
          any: [],
          all: [],
          none: [],
        },
      ],
    }
    expect(() =>
      assertNoPageViolations({
        violations: [transformerFalsePositive],
        passes: [],
        incomplete: [],
      }),
    ).not.toThrow()
  })

  it('throws when a critical violation is present', () => {
    const criticalViolation = {
      id: 'image-alt',
      impact: 'critical' as const,
      tags: [],
      description: 'Images must have alternate text',
      help: 'Image elements must have an alt attribute',
      helpUrl: 'https://dequeuniversity.com/rules/axe/4.9/image-alt',
      nodes: [
        {
          target: ['img'],
          html: '<img src="food.jpg">',
          failureSummary: 'Fix any of the following: Element does not have an alt attribute',
          impact: 'critical' as const,
          any: [],
          all: [],
          none: [],
        },
      ],
    }
    expect(() =>
      assertNoPageViolations({
        violations: [criticalViolation],
        passes: [],
        incomplete: [],
      }),
    ).toThrow(/image-alt/)
  })

  it('throws when a serious non-false-positive violation is present', () => {
    const seriousViolation = {
      id: 'label',
      impact: 'serious' as const,
      tags: [],
      description: 'Form elements must have labels',
      help: 'Ensure every form element has a label',
      helpUrl: 'https://dequeuniversity.com/rules/axe/4.9/label',
      nodes: [
        {
          target: ['input[type="text"]'],
          html: '<input type="text">',
          failureSummary:
            'Fix any of the following: Form element does not have an implicit (wrapped) label',
          impact: 'serious' as const,
          any: [],
          all: [],
          none: [],
        },
      ],
    }
    expect(() =>
      assertNoPageViolations({
        violations: [seriousViolation],
        passes: [],
        incomplete: [],
      }),
    ).toThrow(/label/)
  })

  it('throws when both a false positive and a real critical violation are present', () => {
    const falsePositive = {
      id: 'aria-prohibited-attr',
      impact: 'serious' as const,
      tags: [],
      description: 'Ensure ARIA attributes are not prohibited',
      help: 'ARIA attributes must not be prohibited',
      helpUrl: 'https://dequeuniversity.com/rules/axe/4.11/aria-prohibited-attr',
      nodes: [],
    }
    const realViolation = {
      id: 'image-alt',
      impact: 'critical' as const,
      tags: [],
      description: 'Images must have alternate text',
      help: 'Image elements must have an alt attribute',
      helpUrl: 'https://dequeuniversity.com/rules/axe/4.9/image-alt',
      nodes: [],
    }
    expect(() =>
      assertNoPageViolations({
        violations: [falsePositive, realViolation],
        passes: [],
        incomplete: [],
      }),
    ).toThrow(/image-alt/)
  })
})
