import { describe, expect, it } from 'vitest'
import { assembleProcedures } from '@server/lib/agents/assembler'
import type { CustomProcedureSpec } from '@server/lib/agents/feature-schema'

describe('assembleProcedures', () => {
  const existingRouter = `// Auto-generated by VibeStack — do not edit manually

import { z } from 'zod'
import { eq } from 'drizzle-orm'
import { task } from '../../db/schema'
import { router, protectedProcedure } from '../trpc'

export const taskRouter = router({
  list: protectedProcedure.query(async ({ ctx }) => {
    return ctx.db.query.task.findMany()
  }),

  // {/* SLOT: CUSTOM_PROCEDURES — LLM backend agent fills search, joins, business logic here */}
})`

  it('replaces SLOT marker with assembled procedures', () => {
    const spec: CustomProcedureSpec = {
      procedures: [
        {
          name: 'search',
          type: 'query',
          access: 'protected',
          description: 'Search tasks by title',
          inputFields: [{ name: 'query', type: 'string', optional: false }],
          implementation: "return ctx.db.query.task.findMany({ where: ilike(task.title, `%${input.query}%`) })",
        },
      ],
    }

    const result = assembleProcedures(existingRouter, spec)
    expect(result).not.toContain('SLOT')
    expect(result).toContain('search: protectedProcedure')
    expect(result).toContain('z.string()')
  })

  it('handles empty procedures array', () => {
    const spec: CustomProcedureSpec = { procedures: [] }
    const result = assembleProcedures(existingRouter, spec)
    expect(result).not.toContain('SLOT')
  })

  it('generates correct Zod input schema', () => {
    const spec: CustomProcedureSpec = {
      procedures: [
        {
          name: 'filter',
          type: 'query',
          access: 'public',
          description: 'Filter by status',
          inputFields: [
            { name: 'status', type: 'string', optional: false },
            { name: 'limit', type: 'number', optional: true },
          ],
          implementation: 'return []',
        },
      ],
    }

    const result = assembleProcedures(existingRouter, spec)
    expect(result).toContain('status: z.string()')
    expect(result).toContain('limit: z.number().optional()')
  })

  it('uses publicProcedure for public access', () => {
    const spec: CustomProcedureSpec = {
      procedures: [
        {
          name: 'count',
          type: 'query',
          access: 'public',
          description: 'Count all',
          inputFields: [],
          implementation: 'return 0',
        },
      ],
    }

    const result = assembleProcedures(existingRouter, spec)
    expect(result).toContain('count: publicProcedure')
  })
})
