// tests/contract-to-drizzle.test.ts
import { describe, it, expect } from 'vitest';
import { contractToDrizzleSchema } from '@/lib/contract-to-drizzle';
import type { SchemaContract } from '@/lib/schema-contract';

describe('contractToDrizzleSchema', () => {
  const contract: SchemaContract = {
    tables: [
      {
        name: 'tasks',
        columns: [
          { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
          { name: 'title', type: 'text', nullable: false },
          { name: 'completed', type: 'boolean', default: 'false' },
          { name: 'user_id', type: 'uuid', references: { table: 'auth.users', column: 'id' } },
          { name: 'created_at', type: 'timestamptz', default: 'now()' },
        ],
        rlsPolicies: [],
      },
    ],
    enums: [{ name: 'task_status', values: ['pending', 'in_progress', 'done'] }],
  };

  it('generates valid Drizzle pgTable imports', () => {
    const result = contractToDrizzleSchema(contract);
    expect(result).toContain("import { pgTable, pgEnum");
    expect(result).toContain("from 'drizzle-orm/pg-core'");
  });

  it('generates pgEnum for contract enums', () => {
    const result = contractToDrizzleSchema(contract);
    expect(result).toContain("export const taskStatusEnum = pgEnum('task_status', ['pending', 'in_progress', 'done'])");
  });

  it('generates pgTable with correct column types', () => {
    const result = contractToDrizzleSchema(contract);
    expect(result).toContain("export const tasks = pgTable('tasks'");
    expect(result).toContain("id: uuid('id').primaryKey().default(sql`gen_random_uuid()`)");
    expect(result).toContain("title: text('title').notNull()");
    expect(result).toContain("completed: boolean('completed').default(false)");
    expect(result).toContain("createdAt: timestamp('created_at', { withTimezone: true }).default(sql`now()`)");
  });

  it('generates foreign key references', () => {
    const result = contractToDrizzleSchema(contract);
    // For external tables like auth.users, we just declare the column without .references()
    expect(result).toContain("userId: uuid('user_id')");
  });

  it('generates type exports using $inferSelect and $inferInsert', () => {
    const result = contractToDrizzleSchema(contract);
    expect(result).toContain("export type Task = typeof tasks.$inferSelect");
    expect(result).toContain("export type NewTask = typeof tasks.$inferInsert");
  });

  it('handles multiple tables in topological order', () => {
    const multiTable: SchemaContract = {
      tables: [
        {
          name: 'comments',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'post_id', type: 'uuid', references: { table: 'posts', column: 'id' } },
            { name: 'body', type: 'text' },
          ],
        },
        {
          name: 'posts',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'title', type: 'text' },
          ],
        },
      ],
    };
    const result = contractToDrizzleSchema(multiTable);
    const postsIdx = result.indexOf("export const posts");
    const commentsIdx = result.indexOf("export const comments");
    expect(postsIdx).toBeLessThan(commentsIdx); // posts before comments (FK order)
  });

  it('generates auto-generated header comment', () => {
    const result = contractToDrizzleSchema(contract);
    expect(result).toContain('// Auto-generated by VibeStack');
  });
});
