// tests/contract-to-hooks.test.ts

import { contractToHooks } from '@server/lib/contract-to-hooks'
import type { SchemaContract } from '@server/lib/schema-contract'
import { describe, expect, it } from 'vitest'

describe('contractToHooks', () => {
  it('generates correct imports', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'task',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
            { name: 'title', type: 'text', nullable: false },
          ],
        },
      ],
    }
    const hooks = contractToHooks(contract)

    expect(hooks).toContain(
      "import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'",
    )
    expect(hooks).toContain("import { supabase } from '@/lib/supabase-browser'")
    expect(hooks).toContain("import type { Database } from '@/lib/types'")
    expect(hooks).toContain('// Auto-generated by VibeStack — do not edit manually')
  })

  it('generates type aliases for each table', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'task',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
            { name: 'title', type: 'text', nullable: false },
          ],
        },
      ],
    }
    const hooks = contractToHooks(contract)

    expect(hooks).toContain("type TaskRow = Database['public']['Tables']['task']['Row']")
    expect(hooks).toContain("type TaskInsert = Database['public']['Tables']['task']['Insert']")
    expect(hooks).toContain("type TaskUpdate = Database['public']['Tables']['task']['Update']")
  })

  it('generates useQuery hooks (list and by-id)', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'task',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
            { name: 'title', type: 'text', nullable: false },
          ],
        },
      ],
    }
    const hooks = contractToHooks(contract)

    // List hook (plural)
    expect(hooks).toContain('export function useTasks()')
    expect(hooks).toContain("queryKey: ['task']")
    expect(hooks).toContain("await supabase.from('task').select('*')")

    // By-id hook (singular)
    expect(hooks).toContain('export function useTaskById(id: string)')
    expect(hooks).toContain("queryKey: ['task', id]")
    expect(hooks).toContain("await supabase.from('task').select('*').eq('id', id).single()")
    expect(hooks).toContain('enabled: !!id')
  })

  it('generates useMutation hooks (create, update, delete)', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'task',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
            { name: 'title', type: 'text', nullable: false },
          ],
        },
      ],
    }
    const hooks = contractToHooks(contract)

    // Create hook
    expect(hooks).toContain('export function useCreateTask()')
    expect(hooks).toContain('const queryClient = useQueryClient()')
    expect(hooks).toContain("await supabase.from('task').insert(values).select().single()")
    expect(hooks).toContain("queryClient.invalidateQueries({ queryKey: ['task'] })")

    // Update hook
    expect(hooks).toContain('export function useUpdateTask()')
    expect(hooks).toContain(
      "await supabase.from('task').update(values).eq('id', id).select().single()",
    )
    expect(hooks).toContain("queryClient.invalidateQueries({ queryKey: ['task', id] })")

    // Delete hook
    expect(hooks).toContain('export function useDeleteTask()')
    expect(hooks).toContain("await supabase.from('task').delete().eq('id', id)")
  })

  it('handles multiple tables', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'task',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
        {
          name: 'user_profile',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
      ],
    }
    const hooks = contractToHooks(contract)

    // Task hooks
    expect(hooks).toContain('export function useTasks()')
    expect(hooks).toContain('export function useTaskById(id: string)')
    expect(hooks).toContain('export function useCreateTask()')
    expect(hooks).toContain('export function useUpdateTask()')
    expect(hooks).toContain('export function useDeleteTask()')

    // UserProfile hooks
    expect(hooks).toContain('export function useUserProfiles()')
    expect(hooks).toContain('export function useUserProfileById(id: string)')
    expect(hooks).toContain('export function useCreateUserProfile()')
    expect(hooks).toContain('export function useUpdateUserProfile()')
    expect(hooks).toContain('export function useDeleteUserProfile()')
  })

  it('uses correct query key patterns', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'task',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
      ],
    }
    const hooks = contractToHooks(contract)

    // List hook uses table name only
    expect(hooks).toContain("queryKey: ['task']")
    // By-id hook uses table name + id
    expect(hooks).toContain("queryKey: ['task', id]")
  })

  it('generates queryClient.invalidateQueries on mutations', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'task',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
      ],
    }
    const hooks = contractToHooks(contract)

    // Create invalidates list
    expect(hooks).toContain('onSuccess: () => {')
    expect(hooks).toContain("queryClient.invalidateQueries({ queryKey: ['task'] })")

    // Update invalidates both list and by-id
    expect(hooks).toContain('onSuccess: (_, { id }) => {')

    // Delete invalidates both list and by-id
    expect(hooks).toContain('onSuccess: (_, id) => {')
  })

  it('handles snake_case to PascalCase conversion', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'user_profile',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
      ],
    }
    const hooks = contractToHooks(contract)

    // Types use PascalCase
    expect(hooks).toContain(
      "type UserProfileRow = Database['public']['Tables']['user_profile']['Row']",
    )
    expect(hooks).toContain(
      "type UserProfileInsert = Database['public']['Tables']['user_profile']['Insert']",
    )
    expect(hooks).toContain(
      "type UserProfileUpdate = Database['public']['Tables']['user_profile']['Update']",
    )

    // Hooks use PascalCase
    expect(hooks).toContain('export function useUserProfiles()')
    expect(hooks).toContain('export function useUserProfileById(id: string)')
    expect(hooks).toContain('export function useCreateUserProfile()')
    expect(hooks).toContain('export function useUpdateUserProfile()')
    expect(hooks).toContain('export function useDeleteUserProfile()')
  })

  it('handles pluralization correctly', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'category',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
        {
          name: 'status',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
      ],
    }
    const hooks = contractToHooks(contract)

    // category → categories
    expect(hooks).toContain('export function useCategories()')
    // status → statuses
    expect(hooks).toContain('export function useStatuses()')
  })

  it('includes error handling in all queries and mutations', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'task',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
      ],
    }
    const hooks = contractToHooks(contract)

    // All query/mutation functions throw on error
    const errorChecks = hooks.match(/if \(error\) throw error/g)
    expect(errorChecks?.length).toBe(5) // list, by-id, create, update, delete
  })
})
