// tests/contract-to-drizzle.test.ts

import { contractToDrizzleSchema } from '@server/lib/contract-to-drizzle'
import type { SchemaContract } from '@server/lib/schema-contract'
import { describe, expect, it } from 'vitest'

describe('contractToDrizzleSchema', () => {
  const contract: SchemaContract = {
    tables: [
      {
        name: 'tasks',
        columns: [
          { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
          { name: 'title', type: 'text', nullable: false },
          { name: 'completed', type: 'boolean', default: 'false' },
          { name: 'user_id', type: 'uuid', references: { table: 'auth.users', column: 'id' } },
          { name: 'created_at', type: 'timestamptz', default: 'now()' },
        ],
        rlsPolicies: [],
      },
    ],
    enums: [{ name: 'task_status', values: ['pending', 'in_progress', 'done'] }],
  }

  it('generates valid Drizzle pgTable imports', () => {
    const result = contractToDrizzleSchema(contract)
    expect(result).toContain('import { pgTable, pgEnum')
    expect(result).toContain("from 'drizzle-orm/pg-core'")
  })

  it('generates pgEnum for contract enums', () => {
    const result = contractToDrizzleSchema(contract)
    expect(result).toContain(
      "export const taskStatusEnum = pgEnum('task_status', ['pending', 'in_progress', 'done'])",
    )
  })

  it('generates pgTable with correct column types', () => {
    const result = contractToDrizzleSchema(contract)
    expect(result).toContain("export const tasks = pgTable('tasks'")
    expect(result).toContain("id: uuid('id').primaryKey().default(sql`gen_random_uuid()`)")
    expect(result).toContain("title: text('title').notNull()")
    expect(result).toContain("completed: boolean('completed').default(false)")
    expect(result).toContain(
      "createdAt: timestamp('created_at', { withTimezone: true }).default(sql`now()`)",
    )
  })

  it('generates foreign key references', () => {
    const result = contractToDrizzleSchema(contract)
    // For external tables like auth.users, we just declare the column without .references()
    expect(result).toContain("userId: uuid('user_id')")
  })

  it('generates type exports using $inferSelect and $inferInsert', () => {
    const result = contractToDrizzleSchema(contract)
    expect(result).toContain('export type Task = typeof tasks.$inferSelect')
    expect(result).toContain('export type NewTask = typeof tasks.$inferInsert')
  })

  it('handles multiple tables in topological order', () => {
    const multiTable: SchemaContract = {
      tables: [
        {
          name: 'comments',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'post_id', type: 'uuid', references: { table: 'posts', column: 'id' } },
            { name: 'body', type: 'text' },
          ],
        },
        {
          name: 'posts',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'title', type: 'text' },
          ],
        },
      ],
    }
    const result = contractToDrizzleSchema(multiTable)
    const postsIdx = result.indexOf('export const posts')
    const commentsIdx = result.indexOf('export const comments')
    expect(postsIdx).toBeLessThan(commentsIdx) // posts before comments (FK order)
  })

  it('generates auto-generated header comment', () => {
    const result = contractToDrizzleSchema(contract)
    expect(result).toContain('// Auto-generated by VibeStack')
  })

  it('handles all column types correctly', () => {
    const allTypes: SchemaContract = {
      tables: [
        {
          name: 'data_types_test',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'name', type: 'text' },
            { name: 'count', type: 'integer' },
            { name: 'big_number', type: 'bigint' },
            { name: 'price', type: 'numeric' },
            { name: 'active', type: 'boolean' },
            { name: 'created_at', type: 'timestamptz' },
            { name: 'metadata', type: 'jsonb' },
          ],
        },
      ],
    }
    const result = contractToDrizzleSchema(allTypes)

    expect(result).toContain("id: uuid('id')")
    expect(result).toContain("name: text('name')")
    expect(result).toContain("count: integer('count')")
    expect(result).toContain("bigNumber: bigint('big_number', { mode: 'number' })")
    expect(result).toContain("price: numeric('price')")
    expect(result).toContain("active: boolean('active')")
    expect(result).toContain("createdAt: timestamp('created_at', { withTimezone: true })")
    expect(result).toContain("metadata: jsonb('metadata')")
  })

  it('handles self-referential foreign keys', () => {
    const selfRef: SchemaContract = {
      tables: [
        {
          name: 'categories',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'name', type: 'text', nullable: false },
            { name: 'parent_id', type: 'uuid', references: { table: 'categories', column: 'id' } },
          ],
        },
      ],
    }
    const result = contractToDrizzleSchema(selfRef)

    // Should include the categories table
    expect(result).toContain("export const categories = pgTable('categories'")
    // Should have self-reference with onDelete cascade
    expect(result).toContain(
      "parentId: uuid('parent_id').references(() => categories.id, { onDelete: 'cascade' })",
    )
  })

  it('adds onDelete cascade to foreign key references', () => {
    const withFk: SchemaContract = {
      tables: [
        {
          name: 'posts',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'title', type: 'text' },
          ],
        },
        {
          name: 'comments',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'post_id', type: 'uuid', references: { table: 'posts', column: 'id' } },
          ],
        },
      ],
    }
    const result = contractToDrizzleSchema(withFk)

    expect(result).toContain(
      "postId: uuid('post_id').references(() => posts.id, { onDelete: 'cascade' })",
    )
  })

  it('handles non-plural words ending in s correctly', () => {
    const nonPlural: SchemaContract = {
      tables: [
        {
          name: 'status',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'value', type: 'text' },
          ],
        },
        {
          name: 'address',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'street', type: 'text' },
          ],
        },
      ],
    }
    const result = contractToDrizzleSchema(nonPlural)

    // Should NOT strip the 's' from status or address
    expect(result).toContain('export type Status = typeof status.$inferSelect')
    expect(result).toContain('export type NewStatus = typeof status.$inferInsert')
    expect(result).toContain('export type Address = typeof address.$inferSelect')
    expect(result).toContain('export type NewAddress = typeof address.$inferInsert')
  })
})
