// tests/contract-to-pages.test.ts

import {
  contractToPages,
  snakeToPascal,
  snakeToCamel,
  snakeToKebab,
  pluralize,
} from '@server/lib/contract-to-pages'
import type { SchemaContract } from '@server/lib/schema-contract'
import { describe, expect, it } from 'vitest'

describe('contractToPages', () => {
  const simpleContract: SchemaContract = {
    tables: [
      {
        name: 'task',
        columns: [
          { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
          { name: 'title', type: 'text', nullable: false },
        ],
      },
    ],
  }

  it('generates two pages per table (list + detail)', () => {
    const pages = contractToPages(simpleContract)

    expect(pages).toHaveLength(2)
    expect(pages[0].fileName).toBe('tasks.tsx')
    expect(pages[1].fileName).toBe('tasks.$id.tsx')
  })

  it('generates correct route paths', () => {
    const pages = contractToPages(simpleContract)

    expect(pages[0].routePath).toBe('/_authenticated/tasks')
    expect(pages[1].routePath).toBe('/_authenticated/tasks/$id')
  })

  it('includes auto-generated comment header', () => {
    const pages = contractToPages(simpleContract)

    expect(pages[0].content).toContain('// Auto-generated by VibeStack')
    expect(pages[1].content).toContain('// Auto-generated by VibeStack')
  })

  it('exports proper Route for TanStack Router', () => {
    const pages = contractToPages(simpleContract)

    expect(pages[0].content).toContain("export const Route = createFileRoute('/_authenticated/tasks')")
    expect(pages[1].content).toContain("export const Route = createFileRoute('/_authenticated/tasks/$id')")
  })

  it('content contains entity name in SLOT comment', () => {
    const pages = contractToPages(simpleContract)

    expect(pages[0].content).toContain('entity: task')
    expect(pages[1].content).toContain('entity: task')
  })


  it('handles snake_case table names with kebab-case conversion', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'user_profile',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
          ],
        },
      ],
    }
    const pages = contractToPages(contract)

    // File names use kebab-case plural
    expect(pages[0].fileName).toBe('user-profiles.tsx')
    expect(pages[1].fileName).toBe('user-profiles.$id.tsx')

    // Route paths use kebab-case plural
    expect(pages[0].routePath).toBe('/_authenticated/user-profiles')
    expect(pages[1].routePath).toBe('/_authenticated/user-profiles/$id')

    // Entity name is preserved in SLOT comment
    expect(pages[0].content).toContain('entity: user_profile')
    expect(pages[1].content).toContain('entity: user_profile')
  })

  it('handles multiple tables', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'task',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
        {
          name: 'project',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
      ],
    }
    const pages = contractToPages(contract)

    expect(pages).toHaveLength(4) // 2 tables × 2 pages each

    // Task pages
    expect(pages[0].fileName).toBe('tasks.tsx')
    expect(pages[1].fileName).toBe('tasks.$id.tsx')
    expect(pages[0].content).toContain('entity: task')
    expect(pages[1].content).toContain('entity: task')

    // Project pages
    expect(pages[2].fileName).toBe('projects.tsx')
    expect(pages[3].fileName).toBe('projects.$id.tsx')
    expect(pages[2].content).toContain('entity: project')
    expect(pages[3].content).toContain('entity: project')
  })

  it('handles pluralization correctly', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'category',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
        {
          name: 'status',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
        {
          name: 'box',
          columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
        },
      ],
    }
    const pages = contractToPages(contract)

    // category → categories (y → ies)
    expect(pages[0].fileName).toBe('categories.tsx')
    expect(pages[0].routePath).toBe('/_authenticated/categories')

    // status → statuses (s → ses)
    expect(pages[2].fileName).toBe('statuses.tsx')
    expect(pages[2].routePath).toBe('/_authenticated/statuses')

    // box → boxes (x → xes)
    expect(pages[4].fileName).toBe('boxes.tsx')
    expect(pages[4].routePath).toBe('/_authenticated/boxes')
  })

  it('exports naming helper functions', () => {
    // Test that naming helpers are exported and work correctly
    expect(snakeToPascal('user_profile')).toBe('UserProfile')
    expect(snakeToCamel('user_profile')).toBe('userProfile')
    expect(snakeToKebab('user_profile')).toBe('user-profile')
    expect(pluralize('task')).toBe('tasks')
    expect(pluralize('category')).toBe('categories')
    expect(pluralize('status')).toBe('statuses')
    expect(pluralize('box')).toBe('boxes')
  })

})
