// tests/contract-to-drizzle.test.ts

import { contractToDrizzle } from '@server/lib/contract-to-drizzle'
import type { SchemaContract } from '@server/lib/schema-contract'
import { describe, expect, it } from 'vitest'

describe('contractToDrizzle', () => {
  it('generates pgTable with correct column types', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'items',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
            { name: 'title', type: 'text', nullable: false },
            { name: 'count', type: 'numeric' },
            { name: 'active', type: 'boolean', default: 'false' },
            { name: 'price', type: 'integer', default: '0' },
            { name: 'views', type: 'bigint' },
            { name: 'metadata', type: 'jsonb' },
            { name: 'created_at', type: 'timestamptz', nullable: false, default: 'now()' },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    // Header comment
    expect(ts).toContain('// Auto-generated by VibeStack')

    // Imports
    expect(ts).toContain("import { uuid, text, numeric, boolean, integer, bigint, jsonb, timestamp, pgTable } from 'drizzle-orm/pg-core'")

    // Table definition
    expect(ts).toContain("export const items = pgTable('items', {")
    expect(ts).toContain("id: uuid('id').primaryKey().defaultRandom(),")
    expect(ts).toContain("title: text('title').notNull(),")
    expect(ts).toContain("count: numeric('count'),")
    expect(ts).toContain("active: boolean('active').default(false),")
    expect(ts).toContain("price: integer('price').default(0),")
    expect(ts).toContain("views: bigint('views', { mode: 'number' }),")
    expect(ts).toContain("metadata: jsonb('metadata'),")
    expect(ts).toContain("createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),")
    expect(ts).toContain('})')
  })

  it('converts snake_case column names to camelCase properties', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'user_profiles',
          columns: [
            { name: 'user_id', type: 'uuid', primaryKey: true },
            { name: 'first_name', type: 'text' },
            { name: 'last_name', type: 'text' },
            { name: 'updated_at', type: 'timestamptz', default: 'now()' },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    // Property names should be camelCase
    expect(ts).toContain("userId: uuid('user_id').primaryKey(),")
    expect(ts).toContain("firstName: text('first_name'),")
    expect(ts).toContain("lastName: text('last_name'),")
    expect(ts).toContain("updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),")
  })

  it('generates FK references between tables', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'posts',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
            { name: 'title', type: 'text', nullable: false },
          ],
        },
        {
          name: 'comments',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
            { name: 'post_id', type: 'uuid', references: { table: 'posts', column: 'id' } },
            { name: 'content', type: 'text' },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    // Posts table should be defined first (topological sort)
    const postsIdx = ts.indexOf('export const posts')
    const commentsIdx = ts.indexOf('export const comments')
    expect(postsIdx).toBeLessThan(commentsIdx)

    // FK reference
    expect(ts).toContain("postId: uuid('post_id').references(() => posts.id),")
  })

  it('skips FK references to auth.users', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'items',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'user_id', type: 'uuid', references: { table: 'auth.users', column: 'id' } },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    // Should NOT have a references() call for auth.users
    expect(ts).not.toContain('.references(')
    expect(ts).toContain("userId: uuid('user_id'),")
  })

  it('generates unique constraints', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'users',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'email', type: 'text', unique: true },
            { name: 'username', type: 'text', unique: true },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    expect(ts).toContain("email: text('email').unique(),")
    expect(ts).toContain("username: text('username').unique(),")
  })

  it('generates pgEnum for enums', () => {
    const contract: SchemaContract = {
      enums: [
        { name: 'status', values: ['active', 'inactive', 'archived'] },
        { name: 'role', values: ['admin', 'user'] },
      ],
      tables: [
        {
          name: 'items',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'title', type: 'text' },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    // Imports should include pgEnum
    expect(ts).toContain('pgEnum')

    // Enum definitions before tables
    expect(ts).toContain("export const statusEnum = pgEnum('status', ['active', 'inactive', 'archived'])")
    expect(ts).toContain("export const roleEnum = pgEnum('role', ['admin', 'user'])")

    const statusIdx = ts.indexOf('statusEnum')
    const tableIdx = ts.indexOf('export const items')
    expect(statusIdx).toBeLessThan(tableIdx)
  })

  it('topologically sorts tables by FK dependencies', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'tags',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'post_id', type: 'uuid', references: { table: 'posts', column: 'id' } },
            { name: 'name', type: 'text' },
          ],
        },
        {
          name: 'comments',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'post_id', type: 'uuid', references: { table: 'posts', column: 'id' } },
          ],
        },
        {
          name: 'posts',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'title', type: 'text' },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    const postsIdx = ts.indexOf('export const posts')
    const commentsIdx = ts.indexOf('export const comments')
    const tagsIdx = ts.indexOf('export const tags')

    // posts must come before comments and tags
    expect(postsIdx).toBeLessThan(commentsIdx)
    expect(postsIdx).toBeLessThan(tagsIdx)
  })

  it('handles boolean default values', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'items',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'active', type: 'boolean', default: 'true' },
            { name: 'archived', type: 'boolean', default: 'false' },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    expect(ts).toContain('active: boolean(\'active\').default(true),')
    expect(ts).toContain('archived: boolean(\'archived\').default(false),')
  })

  it('handles integer default values', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'items',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'count', type: 'integer', default: '42' },
            { name: 'views', type: 'integer', default: '0' },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    expect(ts).toContain('count: integer(\'count\').default(42),')
    expect(ts).toContain('views: integer(\'views\').default(0),')
  })

  it('handles bigint default values', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'items',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'total', type: 'bigint', default: '1000' },
            { name: 'counter', type: 'bigint', default: '0' },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    expect(ts).toContain('total: bigint(\'total\', { mode: \'number\' }).default(1000),')
    expect(ts).toContain('counter: bigint(\'counter\', { mode: \'number\' }).default(0),')
  })

  it('imports only used column types', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'simple',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'name', type: 'text' },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    // Should import uuid, text, pgTable (always), but not others
    expect(ts).toContain('uuid')
    expect(ts).toContain('text')
    expect(ts).toContain('pgTable')
    expect(ts).not.toContain('boolean')
    expect(ts).not.toContain('integer')
    expect(ts).not.toContain('jsonb')
    expect(ts).not.toContain('timestamp')
  })

  it('handles multiple FK references from same table', () => {
    const contract: SchemaContract = {
      tables: [
        {
          name: 'users',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'name', type: 'text' },
          ],
        },
        {
          name: 'posts',
          columns: [
            { name: 'id', type: 'uuid', primaryKey: true },
            { name: 'author_id', type: 'uuid', references: { table: 'users', column: 'id' } },
            { name: 'reviewer_id', type: 'uuid', references: { table: 'users', column: 'id' } },
          ],
        },
      ],
    }
    const ts = contractToDrizzle(contract)

    expect(ts).toContain("authorId: uuid('author_id').references(() => users.id),")
    expect(ts).toContain("reviewerId: uuid('reviewer_id').references(() => users.id),")
  })
})
