/**
 * Remote Database Seeder
 *
 * Uses @snaplet/seed to introspect a remote Supabase Postgres schema
 * and populate it with realistic seed data.
 */

import type { SupabaseProject } from './types';

/**
 * Build a Postgres connection string from Supabase project credentials.
 */
export function buildConnectionString(project: SupabaseProject): string {
  const host = project.dbHost;
  const password = encodeURIComponent(project.dbPassword);
  return `postgresql://postgres:${password}@${host}:5432/postgres`;
}

/**
 * Seed a remote Supabase database with realistic data using @snaplet/seed.
 *
 * Note: @snaplet/seed requires a sync/init step to generate the client.
 * This function provides a type-safe wrapper for runtime usage.
 */
export async function seedRemoteDatabase(
  project: SupabaseProject,
  tableNames: string[],
  rowsPerTable: number = 5,
): Promise<{ tablesSeeded: number; rowsInserted: number }> {
  const connectionString = buildConnectionString(project);

  // Dynamic import to avoid bundling in client
  // Note: createSeedClient() is generated by @snaplet/seed sync
  const { createSeedClient } = await import('@snaplet/seed');

  const seed = await (createSeedClient as any)({
    databaseUrl: connectionString,
  });

  let totalRows = 0;

  for (const tableName of tableNames) {
    try {
      const tableMethod = (seed as any)[tableName];
      if (typeof tableMethod === 'function') {
        await tableMethod((x: any) => x(rowsPerTable));
        totalRows += rowsPerTable;
      }
    } catch (error) {
      console.warn(`[seed-remote] Skipped ${tableName}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  return { tablesSeeded: tableNames.length, rowsInserted: totalRows };
}
