import type { Meta, StoryObj } from '@storybook/react'
import { fn } from '@storybook/test'
import { Code, FileText, Globe, Rocket } from 'lucide-react'
import { ArtifactCard } from './artifact-card'

const meta = {
  title: 'Builder/ArtifactCard',
  component: ArtifactCard,
  tags: ['autodocs'],
  parameters: { layout: 'padded' },
  args: {
    onClick: fn(),
    onAction: fn(),
  },
} satisfies Meta<typeof ArtifactCard>

export default meta
type Story = StoryObj<typeof meta>

export const Default: Story = {
  args: {
    icon: <Rocket className="size-6" />,
    title: 'App Preview',
    meta: 'https://my-app.preview.vibestack.com',
    actionLabel: 'Open Preview',
  },
}

export const CodeFile: Story = {
  args: {
    icon: <Code className="size-6" />,
    title: 'src/components/Dashboard.tsx',
    meta: '142 lines · TypeScript',
    actionLabel: 'View Code',
  },
}

export const Document: Story = {
  args: {
    icon: <FileText className="size-6" />,
    title: 'Product Requirements Document',
    meta: 'Generated by analyst agent',
    actionLabel: 'Open',
  },
}

export const WithoutAction: Story = {
  args: {
    icon: <Globe className="size-6" />,
    title: 'Deployed App',
    meta: 'https://my-app.vercel.app',
  },
}

export const LongTitle: Story = {
  args: {
    icon: <Code className="size-6" />,
    title: 'src/components/really/deeply/nested/SuperLongComponentName.tsx',
    meta: '87 lines · TypeScript React',
    actionLabel: 'View',
  },
}
