import type { ToolStep } from '@/hooks/use-agent-stream'

const now = Date.now()

export const runningSteps: ToolStep[] = [
  {
    id: 'create-sandbox-1',
    tool: 'createSandbox',
    label: 'Creating sandbox environment',
    status: 'complete',
    startedAt: now - 8000,
    durationMs: 3200,
  },
  {
    id: 'write-file-1',
    tool: 'writeFile',
    label: 'Writing file',
    status: 'complete',
    filePath: 'src/components/Button.tsx',
    newContent: `import { cn } from '@/lib/utils'\n\nexport function Button({ children, className, ...props }) {\n  return (\n    <button className={cn('px-4 py-2 rounded', className)} {...props}>\n      {children}\n    </button>\n  )\n}`,
    startedAt: now - 4700,
    durationMs: 820,
  },
  {
    id: 'write-file-2',
    tool: 'writeFiles',
    label: 'Writing multiple files',
    status: 'complete',
    filePath: 'src/app/page.tsx',
    newContent: 'export default function Page() {\n  return <div>Hello World</div>\n}',
    startedAt: now - 3800,
    durationMs: 540,
  },
  {
    id: 'install-pkg-1',
    tool: 'installPackage',
    label: 'Installing packages',
    status: 'complete',
    result: 'Installed react-query, zustand (1240 bytes)',
    startedAt: now - 3200,
    durationMs: 2100,
  },
  {
    id: 'run-build-1',
    tool: 'runBuild',
    label: 'Running build',
    status: 'running',
    startedAt: now - 1000,
  },
]

export const completeSteps: ToolStep[] = [
  {
    id: 'create-sandbox-2',
    tool: 'createSandbox',
    label: 'Creating sandbox environment',
    status: 'complete',
    startedAt: now - 12000,
    durationMs: 3100,
  },
  {
    id: 'web-search-1',
    tool: 'webSearch',
    label: 'Searching for Tailwind v4 docs',
    status: 'complete',
    result: 'Found 5 results',
    startedAt: now - 8800,
    durationMs: 412,
  },
  {
    id: 'write-file-3',
    tool: 'writeFile',
    label: 'Writing file',
    status: 'complete',
    filePath: 'src/components/Header.tsx',
    oldContent: 'export function Header() {\n  return <header>Old Header</header>\n}',
    newContent: 'export function Header() {\n  return (\n    <header className="border-b">\n      <h1>My App</h1>\n    </header>\n  )\n}',
    startedAt: now - 8300,
    durationMs: 670,
  },
  {
    id: 'read-file-1',
    tool: 'readFile',
    label: 'Reading file',
    status: 'complete',
    filePath: 'src/lib/utils.ts',
    result: 'Read 1420 bytes',
    startedAt: now - 7500,
    durationMs: 90,
  },
  {
    id: 'run-build-2',
    tool: 'runBuild',
    label: 'Running build',
    status: 'complete',
    result: 'Build succeeded in 4.2s',
    startedAt: now - 7300,
    durationMs: 4200,
  },
]

export const errorSteps: ToolStep[] = [
  {
    id: 'create-sandbox-3',
    tool: 'createSandbox',
    label: 'Creating sandbox environment',
    status: 'complete',
    startedAt: now - 10000,
    durationMs: 2900,
  },
  {
    id: 'write-file-bad',
    tool: 'editFile',
    label: 'Editing file',
    status: 'complete',
    filePath: 'src/components/Form.tsx',
    newContent: 'export function Form() {\n  return <form>Bad content</form>\n}',
    startedAt: now - 6900,
    durationMs: 310,
  },
  {
    id: 'run-build-bad',
    tool: 'runBuild',
    label: 'Running build',
    status: 'error',
    result: 'TypeScript error: TS2345 in src/components/Form.tsx',
    startedAt: now - 6500,
    durationMs: 1800,
  },
  {
    id: 'list-files-1',
    tool: 'listFiles',
    label: 'Listing files',
    status: 'complete',
    result: '12 files found',
    startedAt: now - 4600,
    durationMs: 55,
  },
  {
    id: 'run-cmd-1',
    tool: 'runCommand',
    label: 'Running command',
    status: 'error',
    result: 'Command exited with code 1',
    startedAt: now - 4500,
    durationMs: 420,
  },
]
