import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { stripIndent } from 'common-tags'
import { inferFeatures, type SchemaContract, type InferredFeatures } from './schema-contract'
import { contractToPages } from './contract-to-pages'
import { contractToSQL } from './contract-to-sql'
import { snakeToPascal, snakeToKebab, pluralize } from './naming-utils'
import { generateThemedApp, type DesignSystem, DEFAULT_TEXT_SLOTS } from './themed-code-engine'
import { runArchitect } from './agents/orchestrator'
import { generatePages } from './page-generator'
import { assembleApp } from './deterministic-assembly'
import { fetchHeroImages } from './unsplash'
import { validateGeneratedApp } from './page-validator'

// ============================================================================
// UI Kit — shadcn/ui components read from snapshot/ui-kit/ at runtime
// ============================================================================

const UI_KIT_DIR = join(import.meta.dirname, '../../snapshot/ui-kit')

/** Read all shadcn/ui component files from snapshot/ui-kit/ */
function loadUIKit(): BlueprintFile[] {
  const files: BlueprintFile[] = []
  const entries = readdirSync(UI_KIT_DIR)
  for (const entry of entries) {
    const content = readFileSync(join(UI_KIT_DIR, entry), 'utf-8')
    // utils.ts → src/lib/utils.ts, everything else → src/components/ui/{name}
    const destPath = entry === 'utils.ts'
      ? 'src/lib/utils.ts'
      : `src/components/ui/${entry}`
    files.push({ path: destPath, content, layer: 1, isLLMSlot: false })
  }
  return files
}

export interface BlueprintFile {
  path: string
  content: string
  layer: number
  isLLMSlot: boolean
}

export interface AppBlueprint {
  meta: {
    appName: string
    appDescription: string
    tokens?: DesignSystem
  }
  features: InferredFeatures
  contract: SchemaContract
  fileTree: BlueprintFile[]
}

interface BlueprintInput {
  appName: string
  appDescription: string
  userPrompt?: string
  contract: SchemaContract
}

/**
 * Fallback theme tokens used when the Design Agent is unavailable.
 * Uses theme-stratton (business/corporate) defaults — neutral and safe.
 */
function fallbackDesignSystem(_input: BlueprintInput): DesignSystem {
  return {
    name: 'theme-stratton',
    fonts: {
      display: 'DM Sans',
      body: 'Inter',
      googleFontsUrl: 'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Inter:wght@400;500;600;700&display=swap',
    },
    colors: {
      background: '#ffffff',
      foreground: '#111111',
      text: '#111111',
      primary: '#1e40af',
      primaryForeground: '#ffffff',
      secondary: '#f1f5f9',
      accent: '#3b82f6',
      muted: '#f8fafc',
      border: '#e2e8f0',
    },
    style: {
      borderRadius: '0.5rem',
      cardStyle: 'elevated',
      navStyle: 'top-bar',
      heroLayout: 'split',
      spacing: 'normal',
      motion: 'subtle',
      imagery: 'minimal',
    },
    aestheticDirection: 'warm-neutral' as const,
    layoutStrategy: 'full-bleed' as const,
    signatureDetail: 'Subtle scroll-triggered reveal animations on content sections',
    imageManifest: {},
    authPosture: 'hybrid',
    heroImages: [],
    heroQuery: 'modern web application',
    textSlots: { ...DEFAULT_TEXT_SLOTS },
  }
}

// ============================================================================
// Color utilities — hex → oklch conversion for Tailwind v4 @theme (via culori)
// ============================================================================

// buildColorPalette + generateIndexCSS removed — themeCss() from themed-code-engine is the sole CSS source.
// Design Agent is the sole authority for visual identity (colors, fonts, layout).

/** Generate index.html for the Vite SPA with optional Google Fonts */
function generateIndexHTML(appName: string, fontsUrl: string): string {
  return stripIndent`<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="${appName}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="${fontsUrl}" rel="stylesheet">
    <title>${appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
}

/** Generate main.tsx with providers and router */
function generateMainTSX(_features: InferredFeatures): string {
  // Auth is handled by Supabase RLS + session tokens (auto-attached by supabase-js).
  // No AuthProvider needed — the _authenticated route guard checks session in beforeLoad.
  return stripIndent`// Auto-generated by VibeStack — do not edit manually
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'
import './index.css'

const queryClient = new QueryClient()
const router = createRouter({ routeTree, scrollRestoration: true })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
)
`
}

/** Generate app-layout.tsx with branded nav and optional sign-out button */
function generateAppLayout(appName: string, features: InferredFeatures): string {
  void appName
  void features
  return stripIndent`// Auto-generated by VibeStack — do not edit manually
import { Outlet } from '@tanstack/react-router'

export function AppLayout() {
  return <Outlet />
}
`
}

/** Generate .env with placeholder credentials (replaced by infra provisioning) */
function generateDotEnv(): string {
  return stripIndent`# Auto-generated — values injected by VibeStack infra provisioning
VITE_SUPABASE_URL=__PLACEHOLDER__
VITE_SUPABASE_ANON_KEY=__PLACEHOLDER__
`
}

/** Generate root route for TanStack Router */
function generateRootRoute(): string {
  return stripIndent`// Auto-generated by VibeStack
import { createRootRoute, Outlet } from '@tanstack/react-router'

export const Route = createRootRoute({
  component: () => <Outlet />,
})
`
}

/** Generate routeTree.gen.ts — deterministic route tree from contract entities.
 *
 * TanStack Router v1.160+ requires `.update()` on each route to set id/path/getParentRoute.
 * Without this, createFileRoute() routes have no path info and all resolve to __root__,
 * causing "Duplicate routes found with id: __root__" at runtime.
 */
function isPrivateTableForTheme(
  table: SchemaContract['tables'][number],
  tokens: DesignSystem,
): boolean {
  if (tokens.authPosture === 'private') return true
  if (tokens.authPosture === 'public') return false

  const hasUserColumn = table.columns.some((column) => column.name === 'user_id')
  const hasAuthReference = table.columns.some((column) => column.references?.table === 'auth.users')
  const hasRlsAuthUid = (table.rlsPolicies ?? []).some((policy) => {
    const using = policy.using?.toLowerCase() ?? ''
    const withCheck = policy.withCheck?.toLowerCase() ?? ''
    return using.includes('auth.uid()') || withCheck.includes('auth.uid()')
  })

  return hasUserColumn || hasAuthReference || hasRlsAuthUid
}

function generateRouteTree(contract: SchemaContract, features: InferredFeatures, tokens: DesignSystem): string {
  const lines: string[] = [
    '/* eslint-disable */',
    '// @ts-nocheck',
    '// This file is auto-generated by VibeStack — do not edit manually',
    '',
    "import { Route as rootRoute } from './routes/__root'",
    "import { Route as IndexImport } from './routes/index'",
    "import { Route as AboutImport } from './routes/about'",
    "import { Route as ContactImport } from './routes/contact'",
  ]

  const authRequired = tokens.authPosture !== 'public'
  const privateTables = contract.tables.filter((table) => isPrivateTableForTheme(table, tokens))
  const publicTables = contract.tables.filter((table) => !isPrivateTableForTheme(table, tokens))

  if (authRequired) {
    lines.push("import { Route as AuthenticatedImport } from './routes/_authenticated/route'")
    lines.push("import { Route as DashboardImport } from './routes/_authenticated/dashboard'")
    lines.push("import { Route as AuthLoginImport } from './routes/auth/login'")
    lines.push("import { Route as AuthSignupImport } from './routes/auth/signup'")
  }

  for (const table of publicTables) {
    const plural = pluralize(table.name)
    const kebab = snakeToKebab(plural)
    const pascal = snakeToPascal(plural)
    lines.push(`import { Route as ${pascal}ListImport } from './routes/${kebab}/index'`)
    lines.push(`import { Route as ${pascal}DetailImport } from './routes/${kebab}/$id'`)
  }

  for (const table of privateTables) {
    const plural = pluralize(table.name)
    const kebab = snakeToKebab(plural)
    const pascal = snakeToPascal(plural)
    lines.push(`import { Route as Private${pascal}ListImport } from './routes/_authenticated/${kebab}/index'`)
    lines.push(`import { Route as Private${pascal}DetailImport } from './routes/_authenticated/${kebab}/$id'`)
  }

  lines.push('')
  lines.push("const IndexRoute = IndexImport.update({ id: '/', path: '/', getParentRoute: () => rootRoute } as any)")
  lines.push("const AboutRoute = AboutImport.update({ path: '/about', getParentRoute: () => rootRoute } as any)")
  lines.push("const ContactRoute = ContactImport.update({ path: '/contact', getParentRoute: () => rootRoute } as any)")

  if (authRequired) {
    lines.push("const AuthenticatedRoute = AuthenticatedImport.update({ id: '/_authenticated', getParentRoute: () => rootRoute } as any)")
    lines.push("const DashboardRoute = DashboardImport.update({ path: '/dashboard', getParentRoute: () => AuthenticatedRoute } as any)")
    lines.push("const AuthLoginRoute = AuthLoginImport.update({ path: '/auth/login', getParentRoute: () => rootRoute } as any)")
    lines.push("const AuthSignupRoute = AuthSignupImport.update({ path: '/auth/signup', getParentRoute: () => rootRoute } as any)")
  }

  lines.push('')

  const publicChildren: string[] = []
  for (const table of publicTables) {
    const plural = pluralize(table.name)
    const kebab = snakeToKebab(plural)
    const pascal = snakeToPascal(plural)
    lines.push(`const ${pascal}ListRoute = ${pascal}ListImport.update({ path: '/${kebab}/', getParentRoute: () => rootRoute } as any)`)
    lines.push(`const ${pascal}DetailRoute = ${pascal}DetailImport.update({ path: '/${kebab}/$id', getParentRoute: () => rootRoute } as any)`)
    publicChildren.push(`  ${pascal}ListRoute,`)
    publicChildren.push(`  ${pascal}DetailRoute,`)
  }

  const privateChildren: string[] = []
  for (const table of privateTables) {
    const plural = pluralize(table.name)
    const kebab = snakeToKebab(plural)
    const pascal = snakeToPascal(plural)
    lines.push(`const Private${pascal}ListRoute = Private${pascal}ListImport.update({ path: '/${kebab}/', getParentRoute: () => AuthenticatedRoute } as any)`)
    lines.push(`const Private${pascal}DetailRoute = Private${pascal}DetailImport.update({ path: '/${kebab}/$id', getParentRoute: () => AuthenticatedRoute } as any)`)
    privateChildren.push(`    Private${pascal}ListRoute,`)
    privateChildren.push(`    Private${pascal}DetailRoute,`)
  }

  lines.push('')
  lines.push('export const routeTree = rootRoute.addChildren([')
  lines.push('  IndexRoute,')
  lines.push('  AboutRoute,')
  lines.push('  ContactRoute,')
  lines.push(...publicChildren)
  if (authRequired) {
    lines.push('  AuthLoginRoute,')
    lines.push('  AuthSignupRoute,')
    lines.push('  AuthenticatedRoute.addChildren([')
    lines.push('    DashboardRoute,')
    lines.push(...privateChildren)
    lines.push('  ]),')
  }
  lines.push('])')
  lines.push('')

  return lines.join('\n')
}

/** Generate Supabase client singleton for the generated app */
function generateSupabaseClient(): string {
  return stripIndent`// Auto-generated by VibeStack
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
`
}

/** Generate Vite config — no TanStack Router plugin (we generate routeTree.gen.ts deterministically) */
function generateViteConfig(): string {
  return stripIndent`import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },
  server: {
    host: '0.0.0.0',
    port: 3000,
    allowedHosts: true,
    cors: true,
  },
})
`
}

/**
 * Generate a complete AppBlueprint from SchemaContract + design preferences.
 * The blueprint contains every file the generated app needs, organized by dependency layer.
 */
async function buildBlueprintFromTokens(input: BlueprintInput, tokens: DesignSystem): Promise<AppBlueprint> {
  const features = inferFeatures(input.contract)
  const themedFiles = await generateThemedApp(input.contract, tokens, input.appName, input.appDescription)
  const fileTree: BlueprintFile[] = []

  // Layer 0: Build config + Vite config + Vercel SPA rewrite (overwrite snapshot defaults)
  fileTree.push({
    path: '.gitignore',
    content: `# Dependencies
node_modules/
.pnp
.pnp.js

# Build output
dist/
dist-ssr/
*.local

# Environment files — use Vercel env vars for secrets
.env
.env.local
.env.*.local

# Vite caches
.vite/

# Editor / OS
.DS_Store
Thumbs.db
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
`,
    layer: 0,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'vite.config.ts',
    content: generateViteConfig(),
    layer: 0,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'vercel.json',
    content: `{
  "rewrites": [{ "source": "/(.*)", "destination": "/index.html" }]
}
`,
    layer: 0,
    isLLMSlot: false,
  })

  // Layer 1: Supabase client + CSS + HTML (all independent)
  fileTree.push({
    path: 'src/lib/supabase.ts',
    content: generateSupabaseClient(),
    layer: 1,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'src/index.css',
    content: themedFiles['src/index.css'],
    layer: 1,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'index.html',
    content: generateIndexHTML(input.appName, tokens.fonts.googleFontsUrl),
    layer: 1,
    isLLMSlot: false,
  })

  // Layer 1 (continued): shadcn/ui components — CRUD pages import from @/components/ui/*
  fileTree.push(...loadUIKit())

  // Layer 2: .env + SQL migration (depend on schema)
  fileTree.push({
    path: '.env',
    content: generateDotEnv(),
    layer: 2,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'supabase/migrations/0001_initial.sql',
    content: contractToSQL(input.contract),
    layer: 2,
    isLLMSlot: false,
  })

  // Layer 0 (continued): Override warmup scaffold App.tsx to prevent duplicate createRootRoute()
  // The snapshot's App.tsx creates its own root route for Vite dep pre-bundling.
  // We replace it with an empty re-export to avoid "Duplicate routes with id: __root__" errors.
  fileTree.push({
    path: 'src/App.tsx',
    content: '// Replaced by VibeStack — see main.tsx\nexport default function App() { return null }\n',
    layer: 0,
    isLLMSlot: false,
  })

  // Layer 3: Root route + themed pages
  fileTree.push({
    path: 'src/routes/__root.tsx',
    content: generateRootRoute(),
    layer: 3,
    isLLMSlot: false,
  })
  for (const [path, content] of Object.entries(themedFiles)) {
    if (path === 'src/index.css') continue
    fileTree.push({
      path,
      content,
      layer: 4,
      isLLMSlot: false,
    })
  }

  // Compatibility layer: keep legacy SLOT files so downstream dry-run/repair flows
  // that still expect assembler paths continue to work during migration.
  const legacyPages = contractToPages(input.contract)
  for (const page of legacyPages) {
    fileTree.push({
      path: `src/routes/_authenticated/${page.fileName}`,
      content: page.content,
      layer: 4,
      isLLMSlot: true,
    })
  }

  // Layer 5: Route tree + wiring files (depend on routes being defined)
  fileTree.push({
    path: 'src/routeTree.gen.ts',
    content: generateRouteTree(input.contract, features, tokens),
    layer: 5,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'src/main.tsx',
    content: generateMainTSX(features),
    layer: 5,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'src/components/app-layout.tsx',
    content: generateAppLayout(input.appName, features),
    layer: 5,
    isLLMSlot: false,
  })

  return {
    meta: {
      appName: input.appName,
      appDescription: input.appDescription,
      tokens,
    },
    features,
    contract: input.contract,
    fileTree,
  }
}

export async function contractToBlueprint(input: BlueprintInput): Promise<AppBlueprint> {
  return buildBlueprintFromTokens(input, fallbackDesignSystem(input))
}

export async function contractToBlueprintCreative(input: BlueprintInput): Promise<AppBlueprint> {
  const userPrompt = input.userPrompt?.trim() || `${input.appName}. ${input.appDescription}`

  // 1. Run Creative Director (single design authority — produces both spec and tokens)
  const { spec, tokens } = await runArchitect({ appName: input.appName, prd: userPrompt })
  console.log(`[blueprint:creative] pages: ${spec.sitemap.length}`)

  // 2.5. Fetch Unsplash images in parallel with nothing — fast standalone call
  // Extract domain keywords from user prompt — Unsplash needs short, generic queries
  const promptFirstLine = (input.userPrompt ?? input.appName ?? 'website').split(/[.\n]/)[0].slice(0, 60).trim()
  const imageQuery = promptFirstLine
  const heroImages = await fetchHeroImages(imageQuery, 10)
  const imagePool = heroImages.map((img) => img.url)
  console.log(`[blueprint:creative] Fetched ${imagePool.length} Unsplash images`)

  // 3. Generate pages in parallel
  const pageResult = await generatePages({
    spec,
    tokens,
  })
  const generatedPages = pageResult.pages
  console.log(`[blueprint:creative] Generated ${generatedPages.length} pages`)

  // 4. Assemble deterministic files
  const assembledFiles = assembleApp({
    spec,
    generatedPages,
    appName: input.appName,
    tokens,
    includeUiKit: true,
  })
  console.log(`[blueprint:creative] Assembled ${assembledFiles.length} files`)

  // 5. Validate
  const fileMap = new Map(assembledFiles.map((f) => [f.path, f.content]))
  const validRoutes = spec.sitemap.map((p) => p.route)
  const validation = validateGeneratedApp({
    files: fileMap,
    validRoutes,
    hasSupabase: false,
  })

  if (validation.warnings.length > 0) {
    for (const warning of validation.warnings) {
      console.log(`[blueprint:creative] Warning [${warning.type}] ${warning.file}: ${warning.message}`)
    }
  }

  if (!validation.valid) {
    const errorSummary = validation.errors
      .map((e) => `${e.file}:${e.line ?? '?'} [${e.type}] ${e.message}`)
      .join('\n')
    throw new Error(`[blueprint:creative] Validation failed with ${validation.errors.length} error(s):\n${errorSummary}`)
  }

  // 6. Merge with infrastructure files
  const features = inferFeatures(input.contract)
  const fileTree: BlueprintFile[] = []

  // Infrastructure: .gitignore, vercel.json
  fileTree.push({
    path: '.gitignore',
    content: `# Dependencies
node_modules/
.pnp
.pnp.js

# Build output
dist/
dist-ssr/
*.local

# Environment files — use Vercel env vars for secrets
.env
.env.local
.env.*.local

# Vite caches
.vite/

# Editor / OS
.DS_Store
Thumbs.db
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
`,
    layer: 0,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'vercel.json',
    content: `{
  "rewrites": [{ "source": "/(.*)", "destination": "/index.html" }]
}
`,
    layer: 0,
    isLLMSlot: false,
  })

  // index.html — fonts are handled by Design Agent tokens; no fonts URL in CreativeSpec
  fileTree.push({
    path: 'index.html',
    content: generateIndexHTML(input.appName, ''),
    layer: 1,
    isLLMSlot: false,
  })

  // .env placeholder
  fileTree.push({
    path: '.env',
    content: generateDotEnv(),
    layer: 2,
    isLLMSlot: false,
  })

  // SQL migration from the merged contract
  fileTree.push({
    path: 'supabase/migrations/0001_initial.sql',
    content: contractToSQL(input.contract),
    layer: 2,
    isLLMSlot: false,
  })

  // UI kit — shadcn/ui components
  fileTree.push(...loadUIKit())

  // App.tsx stub to avoid duplicate createRootRoute() from the snapshot warmup scaffold
  fileTree.push({
    path: 'src/App.tsx',
    content: '// Replaced by VibeStack — see main.tsx\nexport default function App() { return null }\n',
    layer: 0,
    isLLMSlot: false,
  })

  // All assembled files (vite.config, src/index.css, src/main.tsx, src/routeTree.gen.ts,
  // src/routes/__root.tsx, src/lib/supabase.ts, generated pages, auth routes)
  for (const file of assembledFiles) {
    fileTree.push(file)
  }

  // 7. Return AppBlueprint
  return {
    meta: {
      appName: input.appName,
      appDescription: input.appDescription,
      tokens,
    },
    features,
    contract: input.contract,
    fileTree,
  }
}
