import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { inferFeatures, type SchemaContract, type DesignPreferences, type InferredFeatures } from './schema-contract'
import { contractToPages } from './contract-to-pages'
import { contractToSQL } from './contract-to-sql'
import { snakeToPascal, snakeToKebab, pluralize } from './naming-utils'

// ============================================================================
// UI Kit — shadcn/ui components read from snapshot/ui-kit/ at runtime
// ============================================================================

const UI_KIT_DIR = join(import.meta.dirname, '../../snapshot/ui-kit')

/** Read all shadcn/ui component files from snapshot/ui-kit/ */
function loadUIKit(): BlueprintFile[] {
  const files: BlueprintFile[] = []
  const entries = readdirSync(UI_KIT_DIR)
  for (const entry of entries) {
    const content = readFileSync(join(UI_KIT_DIR, entry), 'utf-8')
    // utils.ts → src/lib/utils.ts, everything else → src/components/ui/{name}
    const destPath = entry === 'utils.ts'
      ? 'src/lib/utils.ts'
      : `src/components/ui/${entry}`
    files.push({ path: destPath, content, layer: 1, isLLMSlot: false })
  }
  return files
}

export interface BlueprintFile {
  path: string
  content: string
  layer: number
  isLLMSlot: boolean
}

export interface AppBlueprint {
  meta: {
    appName: string
    appDescription: string
    designPreferences: DesignPreferences
  }
  features: InferredFeatures
  contract: SchemaContract
  fileTree: BlueprintFile[]
}

interface BlueprintInput {
  appName: string
  appDescription: string
  contract: SchemaContract
  designPreferences: DesignPreferences
}

/** Generate Tailwind v4 CSS theme with shadcn/ui color tokens */
function generateIndexCSS(prefs: DesignPreferences): string {
  return `@import "tailwindcss";
@import "tw-animate-css";

@custom-variant dark (&:is(.dark *));

@theme inline {
  --color-background: oklch(1 0 0);
  --color-foreground: oklch(0.145 0 0);
  --color-card: oklch(1 0 0);
  --color-card-foreground: oklch(0.145 0 0);
  --color-popover: oklch(1 0 0);
  --color-popover-foreground: oklch(0.145 0 0);
  --color-primary: oklch(0.205 0 0);
  --color-primary-foreground: oklch(0.985 0 0);
  --color-secondary: oklch(0.97 0 0);
  --color-secondary-foreground: oklch(0.205 0 0);
  --color-muted: oklch(0.97 0 0);
  --color-muted-foreground: oklch(0.556 0 0);
  --color-accent: oklch(0.97 0 0);
  --color-accent-foreground: oklch(0.205 0 0);
  --color-destructive: oklch(0.577 0.245 27.325);
  --color-destructive-foreground: oklch(0.985 0 0);
  --color-border: oklch(0.922 0 0);
  --color-input: oklch(0.922 0 0);
  --color-ring: oklch(0.708 0 0);
  --radius: 0.625rem;
  --font-sans: '${prefs.fontFamily}', ui-sans-serif, system-ui, sans-serif;
}
`
}

/** Generate index.html for the Vite SPA */
function generateIndexHTML(appName: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
}

/** Generate main.tsx with providers and router */
function generateMainTSX(_features: InferredFeatures): string {
  // Auth is handled by Supabase RLS + session tokens (auto-attached by supabase-js).
  // No AuthProvider needed — the _authenticated route guard checks session in beforeLoad.
  return `// Auto-generated by VibeStack — do not edit manually
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'
import './index.css'

const queryClient = new QueryClient()
const router = createRouter({ routeTree })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
)
`
}

/** Generate app-layout.tsx with nav links derived from features */
function generateAppLayout(appName: string, features: InferredFeatures): string {
  const navLinks = features.entities.map((entity) => {
    const plural = pluralize(entity)
    const label = snakeToPascal(plural)
    const kebab = snakeToKebab(plural)
    return `  { to: '/${kebab}', label: '${label}' }`
  }).join(',\n')

  return `// Auto-generated by VibeStack — do not edit manually
import { Link, Outlet } from '@tanstack/react-router'

const navLinks = [
${navLinks},
]

export function AppLayout() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b">
        <nav className="container mx-auto flex items-center gap-6 py-4">
          <Link to="/" className="text-lg font-bold">${appName}</Link>
          {navLinks.map((link) => (
            <Link
              key={link.to}
              to={link.to}
              className="text-sm text-muted-foreground hover:text-foreground"
              activeProps={{ className: 'text-foreground font-medium' }}
            >
              {link.label}
            </Link>
          ))}
        </nav>
      </header>
      <main className="container mx-auto py-6">
        <Outlet />
      </main>
    </div>
  )
}
`
}

/** Generate .env with placeholder credentials (replaced by infra provisioning) */
function generateDotEnv(): string {
  return `# Auto-generated — values injected by VibeStack infra provisioning
VITE_SUPABASE_URL=__PLACEHOLDER__
VITE_SUPABASE_ANON_KEY=__PLACEHOLDER__
`
}

/** Generate root route for TanStack Router */
function generateRootRoute(): string {
  return `// Auto-generated by VibeStack
import { createRootRoute, Outlet } from '@tanstack/react-router'

export const Route = createRootRoute({
  component: () => <Outlet />,
})
`
}

/** Generate index route that redirects to the first entity's list page */
function generateIndexRoute(firstEntityKebab: string): string {
  return `// Auto-generated by VibeStack — redirects to first entity page
import { createFileRoute, redirect } from '@tanstack/react-router'

export const Route = createFileRoute('/')({
  beforeLoad: () => {
    throw redirect({ to: '/${firstEntityKebab}' })
  },
})
`
}

/** Generate routeTree.gen.ts — deterministic route tree from contract entities.
 *
 * TanStack Router v1.160+ requires `.update()` on each route to set id/path/getParentRoute.
 * Without this, createFileRoute() routes have no path info and all resolve to __root__,
 * causing "Duplicate routes found with id: __root__" at runtime.
 */
function generateRouteTree(contract: SchemaContract, features: InferredFeatures): string {
  const lines: string[] = [
    '/* eslint-disable */',
    '// @ts-nocheck',
    '// This file is auto-generated by VibeStack — do not edit manually',
    '',
    "import { Route as rootRoute } from './routes/__root'",
    "import { Route as IndexImport } from './routes/index'",
    "import { Route as AuthenticatedImport } from './routes/_authenticated/route'",
  ]

  // Import each entity's routes
  for (const entity of features.entities) {
    const plural = pluralize(entity)
    const kebab = snakeToKebab(plural)
    const pascal = snakeToPascal(plural)

    lines.push(`import { Route as ${pascal}ListImport } from './routes/_authenticated/${kebab}'`)
    lines.push(`import { Route as ${pascal}DetailImport } from './routes/_authenticated/${kebab}.$id'`)
  }

  // Update routes with path/id/getParentRoute (required by TanStack Router v1.160+)
  lines.push('')
  lines.push("const IndexRoute = IndexImport.update({ id: '/', path: '/', getParentRoute: () => rootRoute } as any)")
  lines.push("const AuthenticatedRoute = AuthenticatedImport.update({ id: '/_authenticated', getParentRoute: () => rootRoute } as any)")
  lines.push('')

  const childRoutes: string[] = []
  for (const entity of features.entities) {
    const plural = pluralize(entity)
    const kebab = snakeToKebab(plural)
    const pascal = snakeToPascal(plural)

    lines.push(`const ${pascal}ListRoute = ${pascal}ListImport.update({ path: '/${kebab}', getParentRoute: () => AuthenticatedRoute } as any)`)
    lines.push(`const ${pascal}DetailRoute = ${pascal}DetailImport.update({ path: '/${kebab}/$id', getParentRoute: () => AuthenticatedRoute } as any)`)

    childRoutes.push(`    ${pascal}ListRoute,`)
    childRoutes.push(`    ${pascal}DetailRoute,`)
  }

  lines.push('')
  lines.push('export const routeTree = rootRoute.addChildren([')
  lines.push('  IndexRoute,')
  lines.push('  AuthenticatedRoute.addChildren([')
  lines.push(...childRoutes)
  lines.push('  ]),')
  lines.push('])')
  lines.push('')

  return lines.join('\n')
}

/** Generate Supabase client singleton for the generated app */
function generateSupabaseClient(): string {
  return `// Auto-generated by VibeStack
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
`
}

/** Generate Vite config — no TanStack Router plugin (we generate routeTree.gen.ts deterministically) */
function generateViteConfig(): string {
  return `import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },
  server: {
    host: '0.0.0.0',
    port: 3000,
    allowedHosts: true,
    cors: true,
  },
})
`
}

/**
 * Generate a complete AppBlueprint from SchemaContract + design preferences.
 * The blueprint contains every file the generated app needs, organized by dependency layer.
 */
export function contractToBlueprint(input: BlueprintInput): AppBlueprint {
  const features = inferFeatures(input.contract)
  const fileTree: BlueprintFile[] = []

  // Layer 0: Build config + Vite config + Vercel SPA rewrite (overwrite snapshot defaults)
  fileTree.push({
    path: 'vite.config.ts',
    content: generateViteConfig(),
    layer: 0,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'vercel.json',
    content: `{
  "rewrites": [{ "source": "/(.*)", "destination": "/index.html" }]
}
`,
    layer: 0,
    isLLMSlot: false,
  })

  // Layer 1: Supabase client + CSS + HTML (all independent)
  fileTree.push({
    path: 'src/lib/supabase.ts',
    content: generateSupabaseClient(),
    layer: 1,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'src/index.css',
    content: generateIndexCSS(input.designPreferences),
    layer: 1,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'index.html',
    content: generateIndexHTML(input.appName),
    layer: 1,
    isLLMSlot: false,
  })

  // Layer 1 (continued): shadcn/ui components — CRUD pages import from @/components/ui/*
  fileTree.push(...loadUIKit())

  // Layer 2: .env + SQL migration (depend on schema)
  fileTree.push({
    path: '.env',
    content: generateDotEnv(),
    layer: 2,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'supabase/migrations/0001_initial.sql',
    content: contractToSQL(input.contract),
    layer: 2,
    isLLMSlot: false,
  })

  // Layer 0 (continued): Override warmup scaffold App.tsx to prevent duplicate createRootRoute()
  // The snapshot's App.tsx creates its own root route for Vite dep pre-bundling.
  // We replace it with an empty re-export to avoid "Duplicate routes with id: __root__" errors.
  fileTree.push({
    path: 'src/App.tsx',
    content: '// Replaced by VibeStack — see main.tsx\nexport default function App() { return null }\n',
    layer: 0,
    isLLMSlot: false,
  })

  // Layer 3: Root route + Index redirect + Auth guard route — deterministic
  fileTree.push({
    path: 'src/routes/__root.tsx',
    content: generateRootRoute(),
    layer: 3,
    isLLMSlot: false,
  })
  // Index route redirects to first entity list page
  const firstEntityKebab = snakeToKebab(pluralize(features.entities[0]))
  fileTree.push({
    path: 'src/routes/index.tsx',
    content: generateIndexRoute(firstEntityKebab),
    layer: 3,
    isLLMSlot: false,
  })
  // _authenticated/route.tsx is ALWAYS needed — all entity routes are nested under it.
  // Even without auth, it serves as the layout wrapper for all pages.
  fileTree.push({
    path: 'src/routes/_authenticated/route.tsx',
    content: `// Auto-generated by VibeStack
import { createFileRoute } from '@tanstack/react-router'
import { AppLayout } from '@/components/app-layout'

export const Route = createFileRoute('/_authenticated')({
  beforeLoad: async () => {
    // Auth check handled by Supabase RLS — session tokens auto-attached by supabase-js
  },
  component: AppLayout,
})
`,
    layer: 3,
    isLLMSlot: false,
  })

  // Layer 4: Page skeletons (LLM fills JSX bodies)
  const pages = contractToPages(input.contract)
  for (const page of pages) {
    fileTree.push({
      path: `src/routes/_authenticated/${page.fileName}`,
      content: page.content,
      layer: 4,
      isLLMSlot: true,
    })
  }

  // Layer 5: Route tree + wiring files (depend on routes being defined)
  fileTree.push({
    path: 'src/routeTree.gen.ts',
    content: generateRouteTree(input.contract, features),
    layer: 5,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'src/main.tsx',
    content: generateMainTSX(features),
    layer: 5,
    isLLMSlot: false,
  })
  fileTree.push({
    path: 'src/components/app-layout.tsx',
    content: generateAppLayout(input.appName, features),
    layer: 5,
    isLLMSlot: false,
  })

  return {
    meta: {
      appName: input.appName,
      appDescription: input.appDescription,
      designPreferences: input.designPreferences,
    },
    features,
    contract: input.contract,
    fileTree,
  }
}
