// lib/contract-to-trpc.ts
import type { SchemaContract, TableDef } from './schema-contract'
import { snakeToCamel, snakeToPascal, snakeToKebab } from './naming-utils'

export interface RouterFile {
  fileName: string
  tableName: string
  content: string
}

/**
 * Check if a table is user-owned (has user_id referencing auth.users).
 */
function isUserOwned(table: TableDef): boolean {
  return table.columns.some(
    (col) =>
      col.name === 'user_id' &&
      col.references?.table === 'auth.users'
  )
}

/**
 * Get sortable columns from a table (exclude JSON/JSONB types).
 */
function getSortableColumns(table: TableDef): string[] {
  return table.columns
    .filter((col) => col.type !== 'jsonb')
    .map((col) => snakeToCamel(col.name))
}

/**
 * Get default sort column (prefer created_at, fallback to id).
 */
function getDefaultSortColumn(table: TableDef): string {
  const hasCreatedAt = table.columns.some((col) => col.name === 'created_at')
  return hasCreatedAt ? 'createdAt' : 'id'
}

/**
 * Generate a tRPC router file for a single table.
 */
export function contractToTrpc(contract: SchemaContract): RouterFile[] {
  return contract.tables.map((table) => {
    const tableName = table.name // snake_case table name from schema
    const camelName = snakeToCamel(tableName) // camelCase for router name
    const pascalName = snakeToPascal(tableName) // PascalCase for schema names
    const fileName = snakeToKebab(tableName) + '.ts'
    const isOwned = isUserOwned(table)
    const procedureType = isOwned ? 'protectedProcedure' : 'publicProcedure'

    // Get sortable columns and default sort
    const sortableColumns = getSortableColumns(table)
    const defaultSort = getDefaultSortColumn(table)
    const sortableColumnsEnum = sortableColumns.map((c) => `'${c}'`).join(', ')

    const lines: string[] = [
      '// Auto-generated by VibeStack — do not edit manually',
      '',
      "import { z } from 'zod'",
      "import { eq, asc, desc, gt, and } from 'drizzle-orm'",
      "import { createInsertSchema } from 'drizzle-orm/zod'",
      `import { ${tableName} } from '../../db/schema'`, // Use snake_case table name for Drizzle import
      `import { router, ${procedureType} } from '../trpc'`,
      '',
      `const insert${pascalName}Schema = createInsertSchema(${tableName})`,
      '',
      `export const ${camelName}Router = router({`,
    ]

    // List query with cursor-based pagination and sorting
    lines.push('  list: ' + procedureType)
    lines.push('    .input(z.object({')
    lines.push('      cursor: z.string().uuid().optional(),')
    lines.push('      limit: z.number().int().min(1).max(100).default(20),')
    lines.push(`      sortBy: z.enum([${sortableColumnsEnum}]).default('${defaultSort}'),`)
    lines.push("      sortOrder: z.enum(['asc', 'desc']).default('desc'),")
    lines.push('    }))')
    lines.push('    .query(async ({ ctx, input }) => {')
    lines.push(`      const orderCol = ${tableName}[input.sortBy]`)
    lines.push('      const orderFn = input.sortOrder === \'asc\' ? asc : desc')
    lines.push('')

    // Build where conditions
    if (isOwned) {
      lines.push('      // Build where conditions')
      lines.push('      const conditions = [')
      lines.push(`        eq(${tableName}.user_id, ctx.userId),`)
      lines.push('      ]')
      lines.push('      if (input.cursor) {')
      lines.push(`        conditions.push(gt(${tableName}.id, input.cursor))`)
      lines.push('      }')
      lines.push('')
      lines.push('      const items = await ctx.db')
      lines.push('        .select()')
      lines.push(`        .from(${tableName})`)
      lines.push('        .where(and(...conditions))')
      lines.push('        .orderBy(orderFn(orderCol))')
      lines.push('        .limit(input.limit + 1)')
    } else {
      lines.push('      let query = ctx.db')
      lines.push('        .select()')
      lines.push(`        .from(${tableName})`)
      lines.push('')
      lines.push('      if (input.cursor) {')
      lines.push(`        query = query.where(gt(${tableName}.id, input.cursor))`)
      lines.push('      }')
      lines.push('')
      lines.push('      const items = await query')
      lines.push('        .orderBy(orderFn(orderCol))')
      lines.push('        .limit(input.limit + 1)')
    }

    lines.push('')
    lines.push('      const hasMore = items.length > input.limit')
    lines.push('      return {')
    lines.push('        items: hasMore ? items.slice(0, -1) : items,')
    lines.push('        nextCursor: hasMore ? items[input.limit - 1].id : null,')
    lines.push('      }')
    lines.push('    }),')
    lines.push('')

    // getById query
    lines.push('  getById: ' + procedureType)
    lines.push('    .input(z.object({ id: z.string().uuid() }))')
    lines.push('    .query(async ({ ctx, input }) => {')
    lines.push(`      return ctx.db.query.${tableName}.findFirst({`) // Use snake_case
    lines.push(`        where: eq(${tableName}.id, input.id),`) // Use snake_case
    lines.push('      })')
    lines.push('    }),')
    lines.push('')

    // create mutation - use drizzle-orm/zod schema
    lines.push('  create: ' + procedureType)
    lines.push(`    .input(insert${pascalName}Schema.omit({ id: true, createdAt: true, updatedAt: true }))`)
    lines.push('    .mutation(async ({ ctx, input }) => {')

    if (isOwned) {
      lines.push(`      const [result] = await ctx.db.insert(${tableName}).values({`) // Use snake_case
      lines.push('        ...input,')
      lines.push('        userId: ctx.userId,')
      lines.push('      }).returning()')
      lines.push('      return result')
    } else {
      lines.push(`      const [result] = await ctx.db.insert(${tableName}).values(input).returning()`) // Use snake_case
      lines.push('      return result')
    }

    lines.push('    }),')
    lines.push('')

    // update mutation - use drizzle-orm/zod schema with partial
    lines.push('  update: ' + procedureType)
    lines.push('    .input(z.object({')
    lines.push('      id: z.string().uuid(),')
    lines.push(`    }).merge(insert${pascalName}Schema.partial().omit({ id: true, createdAt: true, updatedAt: true })))`)
    lines.push('    .mutation(async ({ ctx, input }) => {')
    lines.push('      const { id, ...values } = input')
    lines.push(`      const [result] = await ctx.db.update(${tableName})`) // Use snake_case
    lines.push('        .set(values)')
    lines.push(`        .where(eq(${tableName}.id, id))`) // Use snake_case
    lines.push('        .returning()')
    lines.push('      return result')
    lines.push('    }),')
    lines.push('')

    // delete mutation
    lines.push('  delete: ' + procedureType)
    lines.push('    .input(z.object({ id: z.string().uuid() }))')
    lines.push('    .mutation(async ({ ctx, input }) => {')
    lines.push(`      await ctx.db.delete(${tableName}).where(eq(${tableName}.id, input.id))`) // Use snake_case
    lines.push('    }),')
    lines.push('')

    // SLOT for custom procedures
    lines.push('  // {/* SLOT: CUSTOM_PROCEDURES — LLM backend agent fills search, joins, business logic here */}')
    lines.push('})')

    return {
      fileName,
      tableName,
      content: lines.join('\n'),
    }
  })
}

/**
 * Generate root router that merges all entity routers.
 */
export function contractToRootRouter(contract: SchemaContract): string {
  const lines: string[] = [
    '// Auto-generated by VibeStack — do not edit manually',
    '',
    "import { router } from '../trpc'",
  ]

  // Import all entity routers
  for (const table of contract.tables) {
    const camelName = snakeToCamel(table.name)
    const fileName = snakeToKebab(table.name)
    lines.push(`import { ${camelName}Router } from './routers/${fileName}'`)
  }

  lines.push('')
  lines.push('export const appRouter = router({')

  // Add all routers to the root router
  for (const table of contract.tables) {
    const camelName = snakeToCamel(table.name)
    lines.push(`  ${camelName}: ${camelName}Router,`)
  }

  lines.push('})')
  lines.push('')
  lines.push('export type AppRouter = typeof appRouter')

  return lines.join('\n')
}
