// lib/contract-to-hooks.ts
import type { SchemaContract } from './schema-contract'

/**
 * Convert snake_case to PascalCase.
 * Examples: user_profile → UserProfile, task → Task
 */
function snakeToPascal(str: string): string {
  return str
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
}

/**
 * Simple pluralization: add 's', handle 'y' → 'ies'.
 * Examples: task → tasks, category → categories, status → statuses
 */
function snakeToPlural(str: string): string {
  if (str.endsWith('y')) {
    return str.slice(0, -1) + 'ies'
  }
  if (str.endsWith('s')) {
    return str + 'es'
  }
  return str + 's'
}

/**
 * Generate TanStack Query CRUD hooks from a SchemaContract.
 * Each table gets: useTableNames, useTableNameById, useCreateTableName, useUpdateTableName, useDeleteTableName.
 */
export function contractToHooks(contract: SchemaContract): string {
  const lines: string[] = [
    '// Auto-generated by VibeStack — do not edit manually',
    '',
    "import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'",
    "import { supabase } from '@/lib/supabase-browser'",
    "import type { Database } from '@/lib/types'",
    '',
  ]

  for (const table of contract.tables) {
    const tableName = table.name
    const pascalName = snakeToPascal(tableName)
    const pluralName = snakeToPlural(tableName)
    const pluralPascal = snakeToPascal(pluralName)

    // Type aliases
    lines.push(`type ${pascalName}Row = Database['public']['Tables']['${tableName}']['Row']`)
    lines.push(`type ${pascalName}Insert = Database['public']['Tables']['${tableName}']['Insert']`)
    lines.push(`type ${pascalName}Update = Database['public']['Tables']['${tableName}']['Update']`)
    lines.push('')

    // useTableNames (list all)
    lines.push(`export function use${pluralPascal}() {`)
    lines.push(`  return useQuery<${pascalName}Row[]>({`)
    lines.push(`    queryKey: ['${tableName}'],`)
    lines.push(`    queryFn: async () => {`)
    lines.push(`      const { data, error } = await supabase.from('${tableName}').select('*')`)
    lines.push(`      if (error) throw error`)
    lines.push(`      return data`)
    lines.push(`    },`)
    lines.push(`  })`)
    lines.push(`}`)
    lines.push('')

    // useTableNameById (get by id)
    lines.push(`export function use${pascalName}ById(id: string) {`)
    lines.push(`  return useQuery<${pascalName}Row>({`)
    lines.push(`    queryKey: ['${tableName}', id],`)
    lines.push(`    queryFn: async () => {`)
    lines.push(
      `      const { data, error } = await supabase.from('${tableName}').select('*').eq('id', id).single()`,
    )
    lines.push(`      if (error) throw error`)
    lines.push(`      return data`)
    lines.push(`    },`)
    lines.push(`    enabled: !!id,`)
    lines.push(`  })`)
    lines.push(`}`)
    lines.push('')

    // useCreateTableName (insert)
    lines.push(`export function useCreate${pascalName}() {`)
    lines.push(`  const queryClient = useQueryClient()`)
    lines.push(`  return useMutation<${pascalName}Row, Error, ${pascalName}Insert>({`)
    lines.push(`    mutationFn: async (values) => {`)
    lines.push(
      `      const { data, error } = await supabase.from('${tableName}').insert(values).select().single()`,
    )
    lines.push(`      if (error) throw error`)
    lines.push(`      return data`)
    lines.push(`    },`)
    lines.push(`    onSuccess: () => {`)
    lines.push(`      queryClient.invalidateQueries({ queryKey: ['${tableName}'] })`)
    lines.push(`    },`)
    lines.push(`  })`)
    lines.push(`}`)
    lines.push('')

    // useUpdateTableName (update by id)
    lines.push(`export function useUpdate${pascalName}() {`)
    lines.push(`  const queryClient = useQueryClient()`)
    lines.push(
      `  return useMutation<${pascalName}Row, Error, { id: string; values: ${pascalName}Update }>({`,
    )
    lines.push(`    mutationFn: async ({ id, values }) => {`)
    lines.push(
      `      const { data, error } = await supabase.from('${tableName}').update(values).eq('id', id).select().single()`,
    )
    lines.push(`      if (error) throw error`)
    lines.push(`      return data`)
    lines.push(`    },`)
    lines.push(`    onSuccess: (_, { id }) => {`)
    lines.push(`      queryClient.invalidateQueries({ queryKey: ['${tableName}'] })`)
    lines.push(`      queryClient.invalidateQueries({ queryKey: ['${tableName}', id] })`)
    lines.push(`    },`)
    lines.push(`  })`)
    lines.push(`}`)
    lines.push('')

    // useDeleteTableName (delete by id)
    lines.push(`export function useDelete${pascalName}() {`)
    lines.push(`  const queryClient = useQueryClient()`)
    lines.push(`  return useMutation<void, Error, string>({`)
    lines.push(`    mutationFn: async (id) => {`)
    lines.push(`      const { error } = await supabase.from('${tableName}').delete().eq('id', id)`)
    lines.push(`      if (error) throw error`)
    lines.push(`    },`)
    lines.push(`    onSuccess: (_, id) => {`)
    lines.push(`      queryClient.invalidateQueries({ queryKey: ['${tableName}'] })`)
    lines.push(`      queryClient.invalidateQueries({ queryKey: ['${tableName}', id] })`)
    lines.push(`    },`)
    lines.push(`  })`)
    lines.push(`}`)
    lines.push('')
  }

  return lines.join('\n')
}
