// Auto-generated by VibeStack — do not edit manually
// lib/contract-to-routes.ts

import type { SchemaContract } from './schema-contract'

/**
 * Helper: snake_case → PascalCase
 * Example: user_profile → UserProfile
 */
function snakeToPascal(str: string): string {
  return str
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
}

/**
 * Helper: snake_case → kebab-case
 * Example: user_profile → user-profile
 */
function snakeToKebab(str: string): string {
  return str.replace(/_/g, '-')
}

/**
 * Helper: simple pluralization
 * Example: task → tasks, category → categories
 */
function snakeToPlural(str: string): string {
  // Handle common irregular plurals
  if (str.endsWith('y')) {
    return str.slice(0, -1) + 'ies'
  }
  if (str.endsWith('s') || str.endsWith('sh') || str.endsWith('ch') || str.endsWith('x')) {
    return str + 'es'
  }
  return str + 's'
}

/**
 * Deterministically generates TanStack Router route definitions from a SchemaContract.
 * For each table, generates a list route and detail route.
 *
 * Output format:
 * ```
 * // --- FILE: src/routes/_authenticated/table-name.tsx ---
 * ...list route contents...
 *
 * // --- FILE: src/routes/_authenticated/table-name.$id.tsx ---
 * ...detail route contents...
 * ```
 */
export function contractToRoutes(contract: SchemaContract): string {
  const routes: string[] = []

  for (const table of contract.tables) {
    const tableName = table.name
    const kebabName = snakeToKebab(tableName)
    const pascalName = snakeToPascal(tableName)
    const pluralName = snakeToPlural(tableName)
    const pascalPlural = snakeToPascal(pluralName)

    // Generate list route
    const listRoute = `// --- FILE: src/routes/_authenticated/${kebabName}.tsx ---
import { createFileRoute } from '@tanstack/react-router'
import { use${pascalPlural} } from '@/hooks/use-${snakeToKebab(pluralName)}'

export const Route = createFileRoute('/_authenticated/${kebabName}')({
  component: ${pascalName}ListPage,
})

function ${pascalName}ListPage() {
  const { data: items, isLoading } = use${pascalPlural}()

  if (isLoading) return <div>Loading...</div>

  return (
    <div className="container mx-auto py-6">
      <h1 className="text-2xl font-bold mb-4">${pascalPlural}</h1>
      {/* List items */}
    </div>
  )
}`

    // Generate detail route
    const detailRoute = `// --- FILE: src/routes/_authenticated/${kebabName}.$id.tsx ---
import { createFileRoute } from '@tanstack/react-router'
import { use${pascalName}ById } from '@/hooks/use-${kebabName}'

export const Route = createFileRoute('/_authenticated/${kebabName}/$id')({
  component: ${pascalName}DetailPage,
})

function ${pascalName}DetailPage() {
  const { id } = Route.useParams()
  const { data: item, isLoading } = use${pascalName}ById(id)

  if (isLoading) return <div>Loading...</div>

  return (
    <div className="container mx-auto py-6">
      <h1 className="text-2xl font-bold mb-4">${pascalName} Detail</h1>
      {/* Show item details */}
    </div>
  )
}`

    routes.push(listRoute)
    routes.push(detailRoute)
  }

  return routes.join('\n\n')
}
