// lib/contract-to-pages.ts
import type { SchemaContract } from './schema-contract'
import { snakeToPascal, snakeToCamel, snakeToKebab, pluralize } from './naming-utils'

// Re-export naming helpers for backward compatibility
export { snakeToPascal, snakeToCamel, snakeToKebab, pluralize }

export interface PageFile {
  fileName: string
  routePath: string
  content: string
}

/**
 * Generates page file manifest from a SchemaContract.
 * For each table, generates a list page and detail page file entry with minimal placeholder content.
 * The actual component content will be generated by the assembler during code generation.
 *
 * Returns array of { fileName, routePath, content } objects.
 */
export function contractToPages(contract: SchemaContract): PageFile[] {
  const pages: PageFile[] = []

  for (const table of contract.tables) {
    const tableName = table.name
    const pluralName = pluralize(tableName)
    const pluralKebab = snakeToKebab(pluralName)

    // Generate list page placeholder
    const listPageContent = `// Placeholder — replaced by assembler during code generation
// Route: /_authenticated/${pluralKebab}
// Entity: ${tableName}
export {}
`

    pages.push({
      fileName: `${pluralKebab}.tsx`,
      routePath: `/_authenticated/${pluralKebab}`,
      content: listPageContent,
    })

    // Generate detail page placeholder
    const detailPageContent = `// Placeholder — replaced by assembler during code generation
// Route: /_authenticated/${pluralKebab}/$id
// Entity: ${tableName}
export {}
`

    pages.push({
      fileName: `${pluralKebab}.$id.tsx`,
      routePath: `/_authenticated/${pluralKebab}/$id`,
      content: detailPageContent,
    })
  }

  return pages
}
