// lib/contract-to-pages.ts
import type { SchemaContract } from './schema-contract'
import { snakeToPascal, snakeToCamel, snakeToKebab, pluralize } from './naming-utils'

// Re-export naming helpers for backward compatibility
export { snakeToPascal, snakeToCamel, snakeToKebab, pluralize }

export interface PageFile {
  fileName: string
  routePath: string
  content: string
}

/**
 * Generates page file manifest from a SchemaContract.
 * For each table, generates a list page and detail page file entry with minimal placeholder content.
 * The actual component content will be generated by the assembler during code generation.
 *
 * Returns array of { fileName, routePath, content } objects.
 */
export function contractToPages(contract: SchemaContract): PageFile[] {
  const pages: PageFile[] = []

  for (const table of contract.tables) {
    const tableName = table.name
    const pluralName = pluralize(tableName)
    const pluralKebab = snakeToKebab(pluralName)
    const pascalName = snakeToPascal(pluralName)

    // Generate list page with proper Route export (required for routeTree.gen.ts)
    const listPageContent = `// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/${pluralKebab}')({
  component: ${pascalName}ListPage,
})

function ${pascalName}ListPage() {
  // {/* SLOT: LIST_PAGE — LLM fills component body for entity: ${tableName} */}
  return <div className="p-4">Loading ${pluralKebab}...</div>
}
`

    pages.push({
      fileName: `${pluralKebab}.tsx`,
      routePath: `/_authenticated/${pluralKebab}`,
      content: listPageContent,
    })

    // Generate detail page with proper Route export
    const singularPascal = snakeToPascal(tableName)
    const detailPageContent = `// Auto-generated by VibeStack — SLOT markers replaced by LLM during code generation
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_authenticated/${pluralKebab}/$id')({
  component: ${singularPascal}DetailPage,
})

function ${singularPascal}DetailPage() {
  // {/* SLOT: DETAIL_PAGE — LLM fills component body for entity: ${tableName} */}
  return <div className="p-4">Loading ${tableName} detail...</div>
}
`

    pages.push({
      fileName: `${pluralKebab}.$id.tsx`,
      routePath: `/_authenticated/${pluralKebab}/$id`,
      content: detailPageContent,
    })
  }

  return pages
}
