// lib/contract-to-types.ts
import type { SchemaContract, ColumnDef } from './schema-contract';

const TS_TYPE_MAP: Record<string, string> = {
  uuid: 'string',
  text: 'string',
  numeric: 'number',
  boolean: 'boolean',
  timestamptz: 'string',
  jsonb: 'Record<string, unknown>',
  integer: 'number',
  bigint: 'number',
};

/**
 * Generate a Supabase-compatible `Database` type from a SchemaContract.
 * Produces Row (all fields), Insert (defaults optional), Update (all optional).
 */
export function contractToTypes(contract: SchemaContract): string {
  const lines: string[] = [
    '// Auto-generated by VibeStack — do not edit manually',
    '',
    'export type Database = {',
    '  public: {',
    '    Tables: {',
  ];

  for (const table of contract.tables) {
    lines.push(`      ${table.name}: {`);

    // Row type — all columns, nullable ones get | null
    lines.push('        Row: {');
    for (const col of table.columns) {
      const tsType = TS_TYPE_MAP[col.type] ?? 'unknown';
      const nullable = col.nullable !== false && !col.primaryKey ? ' | null' : '';
      lines.push(`          ${col.name}: ${tsType}${nullable};`);
    }
    lines.push('        };');

    // Insert type — columns with defaults are optional
    lines.push('        Insert: {');
    for (const col of table.columns) {
      const tsType = TS_TYPE_MAP[col.type] ?? 'unknown';
      const nullable = col.nullable !== false && !col.primaryKey ? ' | null' : '';
      const optional = col.default ? '?' : '';
      lines.push(`          ${col.name}${optional}: ${tsType}${nullable};`);
    }
    lines.push('        };');

    // Update type — all optional
    lines.push('        Update: {');
    for (const col of table.columns) {
      const tsType = TS_TYPE_MAP[col.type] ?? 'unknown';
      const nullable = col.nullable !== false && !col.primaryKey ? ' | null' : '';
      lines.push(`          ${col.name}?: ${tsType}${nullable};`);
    }
    lines.push('        };');

    lines.push('      };');
  }

  lines.push('    };');

  // Enums
  lines.push('    Enums: {');
  for (const e of contract.enums ?? []) {
    lines.push(`      ${e.name}: ${e.values.map(v => `'${v}'`).join(' | ')};`);
  }
  lines.push('    };');

  lines.push('  };');
  lines.push('};');

  return lines.join('\n');
}
