// lib/contract-to-trpc.ts
import type { SchemaContract, TableDef, SQLType } from './schema-contract'

export interface RouterFile {
  fileName: string
  tableName: string
  content: string
}

const ZOD_TYPE_MAP: Record<SQLType, string> = {
  uuid: 'z.string().uuid()',
  text: 'z.string()',
  numeric: 'z.number()',
  boolean: 'z.boolean()',
  timestamptz: 'z.string().datetime()',
  jsonb: 'z.record(z.unknown())',
  integer: 'z.number().int()',
  bigint: 'z.number().int()',
}

/**
 * Convert snake_case to camelCase.
 * Examples: user_id → userId, bookmark_tag → bookmarkTag
 */
function snakeToCamel(str: string): string {
  return str.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase())
}



/**
 * Convert snake_case to kebab-case.
 * Examples: bookmark_tag → bookmark-tag
 */
function snakeToKebab(str: string): string {
  return str.replace(/_/g, '-')
}

/**
 * Check if a table is user-owned (has user_id referencing auth.users).
 */
function isUserOwned(table: TableDef): boolean {
  return table.columns.some(
    (col) =>
      col.name === 'user_id' &&
      col.references?.table === 'auth.users'
  )
}

/**
 * Generate Zod input schema fields for create/update operations.
 * Skips: id (primaryKey), created_at, updated_at, user_id (for owned tables).
 */
function generateZodInputFields(table: TableDef, isOwned: boolean): string[] {
  const skipFields = new Set(['id', 'created_at', 'updated_at'])
  if (isOwned) {
    skipFields.add('user_id')
  }

  const fields: string[] = []

  for (const col of table.columns) {
    // Skip auto-managed fields
    if (skipFields.has(col.name) || col.primaryKey) {
      continue
    }

    const camelName = snakeToCamel(col.name)
    const zodType = ZOD_TYPE_MAP[col.type] ?? 'z.unknown()'
    const isOptional = col.nullable !== false || col.default != null

    fields.push(`  ${camelName}: ${zodType}${isOptional ? '.optional()' : ''}`)
  }

  return fields
}

/**
 * Generate a tRPC router file for a single table.
 */
export function contractToTrpc(contract: SchemaContract): RouterFile[] {
  return contract.tables.map((table) => {
    const tableName = table.name // snake_case table name from schema
    const camelName = snakeToCamel(tableName) // camelCase for router name
    const fileName = snakeToKebab(tableName) + '.ts'
    const isOwned = isUserOwned(table)
    const procedureType = isOwned ? 'protectedProcedure' : 'publicProcedure'

    const zodInputFields = generateZodInputFields(table, isOwned)
    const zodSchema = zodInputFields.length > 0
      ? `z.object({\n${zodInputFields.join(',\n')}\n})`
      : 'z.object({})'

    const lines: string[] = [
      '// Auto-generated by VibeStack — do not edit manually',
      '',
      "import { z } from 'zod'",
      "import { eq } from 'drizzle-orm'",
      `import { ${tableName} } from '../../db/schema'`, // Use snake_case table name for Drizzle import
      `import { router, ${procedureType} } from '../trpc'`,
      '',
      `export const ${camelName}Router = router({`,
      '  list: ' + procedureType + '.query(async ({ ctx }) => {',
    ]

    // List query - filter by user_id if owned
    if (isOwned) {
      lines.push(`    return ctx.db.query.${tableName}.findMany({`) // Use snake_case
      lines.push(`      where: eq(${tableName}.user_id, ctx.userId),`) // Use snake_case
      lines.push('    })')
    } else {
      lines.push(`    return ctx.db.query.${tableName}.findMany()`) // Use snake_case
    }

    lines.push('  }),')
    lines.push('')

    // getById query
    lines.push('  getById: ' + procedureType)
    lines.push('    .input(z.object({ id: z.string().uuid() }))')
    lines.push('    .query(async ({ ctx, input }) => {')
    lines.push(`      return ctx.db.query.${tableName}.findFirst({`) // Use snake_case
    lines.push(`        where: eq(${tableName}.id, input.id),`) // Use snake_case
    lines.push('      })')
    lines.push('    }),')
    lines.push('')

    // create mutation
    lines.push('  create: ' + procedureType)
    lines.push(`    .input(${zodSchema})`)
    lines.push('    .mutation(async ({ ctx, input }) => {')

    if (isOwned) {
      lines.push('      const [result] = await ctx.db.insert(' + tableName + ').values({') // Use snake_case
      lines.push('        ...input,')
      lines.push('        userId: ctx.userId,')
      lines.push('      }).returning()')
      lines.push('      return result')
    } else {
      lines.push(`      const [result] = await ctx.db.insert(${tableName}).values(input).returning()`) // Use snake_case
      lines.push('      return result')
    }

    lines.push('    }),')
    lines.push('')

    // update mutation
    lines.push('  update: ' + procedureType)
    lines.push('    .input(z.object({')
    lines.push('      id: z.string().uuid(),')
    lines.push(`      values: ${zodSchema},`)
    lines.push('    }))')
    lines.push('    .mutation(async ({ ctx, input }) => {')
    lines.push(`      const [result] = await ctx.db.update(${tableName})`) // Use snake_case
    lines.push('        .set(input.values)')
    lines.push(`        .where(eq(${tableName}.id, input.id))`) // Use snake_case
    lines.push('        .returning()')
    lines.push('      return result')
    lines.push('    }),')
    lines.push('')

    // delete mutation
    lines.push('  delete: ' + procedureType)
    lines.push('    .input(z.object({ id: z.string().uuid() }))')
    lines.push('    .mutation(async ({ ctx, input }) => {')
    lines.push(`      await ctx.db.delete(${tableName}).where(eq(${tableName}.id, input.id))`) // Use snake_case
    lines.push('    }),')
    lines.push('')

    // SLOT for custom procedures
    lines.push('  // {/* SLOT: CUSTOM_PROCEDURES — LLM backend agent fills search, joins, business logic here */}')
    lines.push('})')

    return {
      fileName,
      tableName,
      content: lines.join('\n'),
    }
  })
}

/**
 * Generate root router that merges all entity routers.
 */
export function contractToRootRouter(contract: SchemaContract): string {
  const lines: string[] = [
    '// Auto-generated by VibeStack — do not edit manually',
    '',
    "import { router } from '../trpc'",
  ]

  // Import all entity routers
  for (const table of contract.tables) {
    const camelName = snakeToCamel(table.name)
    const fileName = snakeToKebab(table.name)
    lines.push(`import { ${camelName}Router } from './routers/${fileName}'`)
  }

  lines.push('')
  lines.push('export const appRouter = router({')

  // Add all routers to the root router
  for (const table of contract.tables) {
    const camelName = snakeToCamel(table.name)
    lines.push(`  ${camelName}: ${camelName}Router,`)
  }

  lines.push('})')
  lines.push('')
  lines.push('export type AppRouter = typeof appRouter')

  return lines.join('\n')
}
