/**
 * GitHub App Client
 *
 * Creates repos in the VibeStackCodes-Generated org using a GitHub App
 * installation token. Octokit handles JWT signing and token caching.
 */

import { createAppAuth } from '@octokit/auth-app'
import { Octokit } from 'octokit'
// buildAppSlug still used by deploy routes (Vercel subdomain naming)

const GITHUB_ORG = process.env.GITHUB_ORG || 'VibeStackCodes-Generated'

let octokitInstance: Octokit | null = null

function getOctokit(): Octokit {
  if (octokitInstance) return octokitInstance

  const appId = process.env.GITHUB_APP_ID
  const privateKey = process.env.GITHUB_APP_PRIVATE_KEY
  const installationId = process.env.GITHUB_APP_INSTALLATION_ID

  if (!appId || !privateKey || !installationId) {
    throw new Error(
      'GITHUB_APP_ID, GITHUB_APP_PRIVATE_KEY, and GITHUB_APP_INSTALLATION_ID are required',
    )
  }

  octokitInstance = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId,
      privateKey,
      installationId: Number(installationId),
    },
  })

  return octokitInstance
}

/**
 * Create a repo in the VibeStackCodes-Generated org.
 * If the name already exists, retries with a random 4-char hex suffix (up to 3 attempts).
 */
export async function createRepo(name: string): Promise<{
  cloneUrl: string
  htmlUrl: string
  repoName: string
}> {
  const octokit = getOctokit()
  const MAX_ATTEMPTS = 3
  let candidateName = name

  for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
    try {
      const { data } = await octokit.rest.repos.createInOrg({
        org: GITHUB_ORG,
        name: candidateName,
        private: false,
        auto_init: false,
        description: 'Generated by VibeStack',
      })

      return {
        cloneUrl: data.clone_url,
        htmlUrl: data.html_url,
        repoName: candidateName,
      }
    } catch (err: unknown) {
      const isNameTaken =
        err instanceof Error &&
        'status' in err &&
        (err as { status: number }).status === 422 &&
        err.message.includes('name already exists')

      if (!isNameTaken || attempt === MAX_ATTEMPTS - 1) throw err

      // Append random hex suffix and retry
      const suffix = Math.random().toString(16).slice(2, 6)
      candidateName = `${name}-${suffix}`
    }
  }

  throw new Error(`Failed to create repo after ${MAX_ATTEMPTS} attempts`)
}

/**
 * Get an installation access token for git push authentication.
 */
export async function getInstallationToken(): Promise<string> {
  const octokit = getOctokit()
  const auth = (await octokit.auth({
    type: 'installation',
  })) as { token: string }
  return auth.token
}

/**
 * Build the repo name from project ID.
 * Format: vibestack-{projectId} — UUIDs guarantee uniqueness.
 */
export function buildRepoName(_appName: string, projectId: string): string {
  return `vibestack-${projectId}`
}
