/**
 * GitHub App Client
 *
 * Creates repos in the VibeStackCodes-Generated org using a GitHub App
 * installation token. Octokit handles JWT signing and token caching.
 */

import { createAppAuth } from '@octokit/auth-app'
import { Octokit } from 'octokit'
import { buildAppSlug } from './slug'

const GITHUB_ORG = process.env.GITHUB_ORG || 'VibeStackCodes-Generated'

let octokitInstance: Octokit | null = null

function getOctokit(): Octokit {
  if (octokitInstance) return octokitInstance

  const appId = process.env.GITHUB_APP_ID
  const privateKey = process.env.GITHUB_APP_PRIVATE_KEY
  const installationId = process.env.GITHUB_APP_INSTALLATION_ID

  if (!appId || !privateKey || !installationId) {
    throw new Error(
      'GITHUB_APP_ID, GITHUB_APP_PRIVATE_KEY, and GITHUB_APP_INSTALLATION_ID are required',
    )
  }

  octokitInstance = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId,
      privateKey,
      installationId: Number(installationId),
    },
  })

  return octokitInstance
}

/**
 * Create a repo in the VibeStackCodes-Generated org.
 */
export async function createRepo(name: string): Promise<{
  cloneUrl: string
  htmlUrl: string
}> {
  const octokit = getOctokit()

  const { data } = await octokit.rest.repos.createInOrg({
    org: GITHUB_ORG,
    name,
    private: false,
    auto_init: false,
    description: 'Generated by VibeStack',
  })

  return {
    cloneUrl: data.clone_url,
    htmlUrl: data.html_url,
  }
}

/**
 * Get an installation access token for git push authentication.
 */
export async function getInstallationToken(): Promise<string> {
  const octokit = getOctokit()
  const auth = (await octokit.auth({
    type: 'installation',
  })) as { token: string }
  return auth.token
}

/**
 * Build the repo name from app name and project ID.
 * Format: vibestack-{app-slug}
 */
export function buildRepoName(appName: string, projectId: string): string {
  return `vibestack-${buildAppSlug(appName, projectId)}`
}
