import type { InjectAnalysis } from './inject'
import type { AppBlueprint, BlueprintFile } from '../app-blueprint'
import { contractToSQL } from '../contract-to-sql'

export interface AdditiveResult {
  /** New files to upload to sandbox (additive only) */
  newFiles: BlueprintFile[]
  /** Files that must be regenerated (nav, route tree) */
  updatedFiles: BlueprintFile[]
  /** Additive SQL migration (CREATE TABLE for new tables only) */
  additiveMigration: string | null
  /** Full SQL migration (for reference/validation, not applied) */
  fullMigration: string
}

/**
 * Given an inject analysis and a full blueprint (generated from the merged capability set),
 * compute the delta — which files are NEW vs which already exist.
 *
 * @param analysis - From analyzeInjection()
 * @param fullBlueprint - Generated by running themed-code-engine with fullAssembly
 * @param existingFilePaths - Set of file paths that already exist in the sandbox
 */
export function computeAdditiveDelta(
  analysis: InjectAnalysis,
  fullBlueprint: AppBlueprint,
  existingFilePaths: Set<string>,
): AdditiveResult {
  if (!analysis.hasChanges || !analysis.additiveAssembly) {
    return {
      newFiles: [],
      updatedFiles: [],
      additiveMigration: null,
      fullMigration: contractToSQL(analysis.fullAssembly.contract),
    }
  }

  const newFiles: BlueprintFile[] = []
  const updatedFiles: BlueprintFile[] = []

  // Files that are ALWAYS regenerated when capabilities change
  const alwaysRegenerate = new Set([
    'src/routes/__root.tsx',           // May have new nav entries
    'src/routeTree.gen.ts',            // Must include new routes
    'src/lib/navigation.ts',           // Nav config if it exists
  ])

  for (const file of fullBlueprint.fileTree) {
    if (alwaysRegenerate.has(file.path)) {
      updatedFiles.push(file)
    } else if (!existingFilePaths.has(file.path)) {
      newFiles.push(file)
    }
    // Files that already exist AND aren't in alwaysRegenerate → skip (don't overwrite)
  }

  // Generate additive migration from ONLY new tables
  const additiveMigration = contractToSQL(analysis.additiveAssembly.contract)

  // Full migration for reference
  const fullMigration = contractToSQL(analysis.fullAssembly.contract)

  return {
    newFiles,
    updatedFiles,
    additiveMigration,
    fullMigration,
  }
}
